### ISSUE TITLE
Fake Kawasaki backend missing qubit data

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1453]
Fake Kawasaki is causing the tests in `test_fake_backends` to fail because of what looks like missing data in `props_kawasaki.json`

It looks like qubit 40 is missing a `T1` value

https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/8106347389/job/22156116132#step:5:2891

```
ImportError: Failed to import test module: test.integration.test_fake_backends
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_fake_backends.py", line 43, in <module>
    class TestFakeBackends(IBMTestCase):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_fake_backends.py", line 58, in TestFakeBackends
    [be for be in FAKE_PROVIDER_FOR_BACKEND_V2.backends() if be.num_qubits > 1],
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_fake_backends.py", line 58, in <listcomp>
    [be for be in FAKE_PROVIDER_FOR_BACKEND_V2.backends() if be.num_qubits > 1],
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/qiskit/providers/backend.py", line 402, in num_qubits
    return self.target.num_qubits
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/fake_provider/fake_backend.py", line 184, in target
    self._target = convert_to_target(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/qiskit/providers/backend_compat.py", line 161, in convert_to_target
    qubit_properties = [
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/qiskit/providers/backend_compat.py", line 163, in <listcomp>
    t1=properties.qubit_property(qubit_idx)["T1"][0],
KeyError: 'T1'
```

**Comment by kt474** [comment]
@mtreinish When you get a chance can you take a look

**Comment by kt474** [comment]
This will be fixed by https://github.com/Qiskit/qiskit/pull/11880, in Qiskit `1.0.2`
