### ISSUE TITLE
Qiskit Runtime Jobs Fail Very Easily Due to Connection Disruptions; WebsocketError

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-ibm-runtime#1518]
Using Qiskit Runtime for for any long duration of time, using locally run python code, does not work (for sequences of experiments that could span more than a couple of hours), in my experience. The primary problem is connection errors, specifically `WebsocketError` and `TimeoutError`. Below is an example partial trace of one of these errors:

```
base_runtime_job._start_websocket_client:WARNING: An error occurred while streaming results from the server for job X:
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/env/lib/python3.10/site-packages/qiskit_ibm_runtime/base_runtime_job.py", line 311, in _start_websocket_client
    self._ws_client.job_results()
  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/qiskit_ibm_runtime/api/clients/runtime_ws.py", line 70, in job_results
    self.stream(url=url, retries=max_retries, backoff_factor=backoff_factor)
  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/qiskit_ibm_runtime/api/clients/base_websocket_client.py", line 222, in stream
    raise WebsocketError(error_message)
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 476, in setSock\n    self.sock.connect(\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_core.py", line 256, in connect\n    self.sock, addrs = connect(\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_http.py", line 141, in connect\n    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_http.py", line 218, in _open_socket\n    raise error\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_http.py", line 205, in _open_socket\n    sock.connect(address)\nTimeoutError: [Errno 60] Operation timed out\n'
```

The problem is that I try to catch these errors in python, specifically when reading result objects, but the source of this particular error originates from somewhere else in the source code so the error is not caught. Either, Qiskit Runtime needs to be more resilient to connection errors, or there needs to be some user facing parameters or flags for handling errors (critically, without the code crashing). The issue is that for specific types of jobs (e.g. variational learning), crashing because of a temporary connection error generally means all of the computation up to that point is lost. 

Edit: Just to clarify, there are a very large number of different network-associated errors that I have encountered. The above example is just the main one I first run into. But, there are some errors that even if I wrap all Qiskit API touchpoints in try-except clauses will still cause the process to hang indefinitely (I suspect, unless maybe the service/backend/something object is re-initialized?). Also, I wanted to mention that I have really only run into these errors for processes that last longer than about 24 hours. Here are some more specific examples of these pernicious errors that I have not been able to mitigate:

```
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 500, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 112, in read\n    if not read_callback():\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 523, in read\n    raise e\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 515, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_core.py", line 437, in recv_data_frame\n    frame = self.recv_frame()\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_core.py", line 478, in recv_frame\n    return self.frame_buffer.recv_frame()\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_abnf.py", line 363, in recv_frame\n    self.recv_header()\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_abnf.py", line 319, in recv_header\n    header = self.recv_strict(2)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_abnf.py", line 398, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_core.py", line 563, in _recv\n    return recv(self.sock, bufsize)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_socket.py", line 129, in recv\n    raise WebSocketConnectionClosedException("Connection to remote host was lost.")\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n'
```

```
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 476, in setSock\n    self.sock.connect(\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_core.py", line 261, in connect\n    self.handshake_response = handshake(self.sock, url, *addrs, **options)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_handshake.py", line 65, in handshake\n    status, resp = _get_resp_headers(sock)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_handshake.py", line 150, in _get_resp_headers\n    raise WebSocketBadStatusException(\nwebsocket._exceptions.WebSocketBadStatusException: Handshake status 503 Service Unavailable -+-+- {\'date\': \’REMOVED GMT\', \'content-type\': \'text/plain\', \'content-length\': \'19\', \'connection\': \'keep-alive\', \'cf-cache-status\': \'DYNAMIC\', \'server\': \'cloudflare\', \'cf-ray\': \’REMOVED-PHX\'} -+-+- b\'no healthy upstream\'\n'
```

```
qiskit_ibm_runtime.exceptions.IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://api.quantum.ibm.com/runtime/sessions/X. {"errors":[{"code":1201,"message":"Invalid credentials.","solution":"Verify your credentials and try again.","more_info":"https://docs.quantum-computing.ibm.com/errors"}]}'
```

```
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 500, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 114, in read\n    check_callback()\n  File "/Users/usr/opt/anaconda3/envs/env/lib/python3.10/site-packages/websocket/_app.py", line 564, in check\n    raise WebSocketTimeoutException("ping/pong timed out")\nwebsocket._exceptions.WebSocketTimeoutException: ping/pong timed out\n'
```
```
qiskit_ibm_runtime.exceptions.IBMRuntimeError: 'Error closing session: "(\'Connection aborted.\', RemoteDisconnected(\'Remote end closed connection without response\'))"'
```

```
"HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/backends/ibm_cusco/status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x...>, 'Connection to api.quantum.ibm.com timed out. (connect timeout=5.0)'))"
'Failed to run program: "HTTPSConnectionPool(host=\'api.quantum.ibm.com\', port=443): Read timed out. (read timeout=900)"'
```

**Steps to reproduce**
Run a Qiskit Runtime job for multiple hours and induce networking connection problems. 

**Suggested solutions**
Add user facing flags for waiting periods and number of retries for dropped connection errors. 

- **qiskit-ibm-runtime version**: 0.21.1
- **Python version**: 3.10
- **Operating system**: macOS

**Comment by jyu00** [comment]
Maybe we can just suppress websocket error since it happens so frequently and websocket is only used to get job status now.

**Comment by epelofske-LANL** [comment]
Does #1627 fix all of the various errors shown above, such as `IBMNotAuthorizedError`?
