### ISSUE TITLE
Legacy staging integration test failures

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#158]
**Describe the bug**
After merging BackendV2 PR the following [tests](https://github.com/Qiskit/qiskit-ibm-runtime/runs/5269111778?check_suite_focus=true#step:5:1249) are failing only on legacy staging with `backend2` (mostly due to an invalid backend config)
```
======================================================================
ERROR: test_backend_invalid_attribute (test.integration.test_backend.TestIBMBackend) (backend='backend2')
Check if AttributeError is raised when an invalid backend attribute is accessed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_backend.py", line 117, in test_backend_invalid_attribute
    backend.foobar  # pylint: disable=pointless-statement
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 193, in __getattr__
    self._convert_to_target()
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 230, in _convert_to_target
    self._target = convert_to_target(
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/utils/backend_converter.py", line 127, in convert_to_target
    target[inst][qarg].calibration = sched
KeyError: (1, 6)

======================================================================
ERROR: test_backend_simulator (test.integration.test_backend.TestIBMBackend) (backend='backend2')
Test if a configuration attribute (ex: simulator) is available as backend attribute.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_backend.py", line 79, in test_backend_simulator
    self.assertIsNotNone(backend.simulator)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 193, in __getattr__
    self._convert_to_target()
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 230, in _convert_to_target
    self._target = convert_to_target(
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/utils/backend_converter.py", line 127, in convert_to_target
    target[inst][qarg].calibration = sched
KeyError: (1, 6)

======================================================================
ERROR: test_backend_target (test.integration.test_backend.TestIBMBackend) (backend='backend2')
Check if the target property is set.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_backend.py", line 66, in test_backend_target
    self.assertIsNotNone(backend.target)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 297, in target
    self._convert_to_target()
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/ibm_backend.py", line 230, in _convert_to_target
    self._target = convert_to_target(
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/utils/backend_converter.py", line 127, in convert_to_target
    target[inst][qarg].calibration = sched
KeyError: (1, 6)
```

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **Qiskit IBM Runtime version**:
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
These tests no longer fail https://github.com/Qiskit/qiskit-ibm-runtime/runs/5364187307?check_suite_focus=true
