### ISSUE TITLE
Unit tests are failing against Qiskit main

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1665]
`test_coder_operators` and `test_circuit_with_multiple_cregs` are failing against the main branch of Qiskit. 

```
ERROR: test_coder_operators (test.unit.test_data_serialization.TestDataSerialization) (operator=SparsePauliOp(['XYZX'],
              coeffs=[ParameterExpression(1.0*x + 1.0)]))
Test runtime encoder and decoder for operators.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/unit/test_data_serialization.py", line 124, in test_coder_operators
    encoded = json.dumps(operator, cls=RuntimeEncoder)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/utils/json.py", line 246, in default
    value = _serialize_and_encode(
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/qiskit_ibm_runtime/utils/json.py", line 110, in _serialize_and_encode
    serializer(buff, data, **kwargs)
TypeError: _write_parameter_expression() missing 1 required keyword-only argument: 'version'
```

```
ERROR: test_circuit_with_multiple_cregs_3 (test.unit.qiskit.test_backend_sampler_v2.TestBackendSamplerV2) [no measure]
Test for circuit with multiple classical registers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/unit/qiskit/test_backend_sampler_v2.py", line 624, in test_circuit_with_multiple_cregs
    self.assertEqual(len(astuple(data)), 3)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/dataclasses.py", line 1139, in astuple
    raise TypeError("astuple() should be called on dataclass instances")
TypeError: astuple() should be called on dataclass instances
```

**Comment by ihincks** [comment]
This will likely be because `make_data_bin` no longer returns a dataclass subclass of `DataBin`. We'll need fixes by 1.1
