### ISSUE TITLE
Accept numpy ndarray as parameter values

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-ibm-runtime#228]
**What is the expected feature or enhancement?**

It would be useful to support numpy ndarray as parameter values because users may generate parameters values by numpy.

current behavior
```python
import numpy as np
from qiskit_ibm_runtime import IBMRuntimeService, IBMEstimator, RuntimeJobFailureError
from qiskit.opflow import PauliSumOp
from qiskit.circuit.library import RealAmplitudes

service = IBMRuntimeService()
estimator_factory = IBMEstimator(service=service, backend="ibmq_qasm_simulator")

observable = PauliSumOp.from_list([("ZZ", 1)])
ansatz = RealAmplitudes(num_qubits=2, reps=2)
param = np.random.rand(1, ansatz.num_parameters)

print(param)

with estimator_factory(circuits=[ansatz], observables=[observable]) as estimator:
    try:
        result = estimator([0], [0], param, shots=1000)  # NG
        print(result)
    except RuntimeJobFailureError as ex:
        print(ex.message)
    result = estimator([0], [0], param.tolist(), shots=1000)  # OK
    print(result)
```

output
```
[[0.39168129 0.98626739 0.70429408 0.42076908 0.67987484 0.28873648]]

Unable to retrieve job result. Job c8tb4tsq5e89jjv606rg has failed:
2022-03-23T00:39:07.845476325-05:00 Traceback (most recent call last):
2022-03-23T00:39:07.845476325-05:00   File "/code/program_starter.py", line 57, in <module>
2022-03-23T00:39:07.845476325-05:00     starter.run(user_params, main)
2022-03-23T00:39:07.845476325-05:00   File "/provider/programruntime/program_starter_wrapper.py", line 86, in run
2022-03-23T00:39:07.845476325-05:00     final_result = main(backend, messenger, **user_params)
2022-03-23T00:39:07.845476325-05:00   File "/code/program.py", line 37, in main
2022-03-23T00:39:07.845476325-05:00     if parameter_values and len(parameter_values) != len(circuit_indices):
2022-03-23T00:39:07.845476325-05:00 ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

EstimatorResult(values=array([0.066]), metadata=[{'variance': 0.995644, 'shots': 1000}])
```

**Acceptance criteria**

**Comment by t-imamichi** [comment]
The script in the description works fine now.
