### ISSUE TITLE
Estimator hangs 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#262]
**Describe the bug**

The estimator seems to hang on the following problem:

```python
from qiskit.quantum_info import Pauli


N = 12
qc = QuantumCircuit(N)
qc.x(range(N))
qc.h(range(N))
qc.ch(range(N//2,0,-1), range(N//2-1,-1,-1))
qc.ch(range(N//2, N-1), range(N//2+1,N))
qc.measure_all()
op = Pauli('Z'*12)

with ibm_estimator(circuits=[qc], observables=[op], skip_transpilation=False) as estimator:
    result = estimator(circuit_indices=[0],
                       observable_indices=[0],
                       parameter_values=None,
                       shots=1e4)
    
result
```

**Steps to reproduce**
Run the above on an IBM Cloud system

**Expected behavior**
It should return an answer, hopefully near `0.446`.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by ajavadia** [comment]
i haven't debugged this but I think `measure_all()` here would not give you the expectation value you want. Since your circuit must prepare the statevector from which you compute the observable.

**Comment by rathishcholarajan** [comment]
Summarizing what we tried today and what we know so far:

1. Program we used to check.
```
from qiskit_ibm_runtime import IBMRuntimeService, IBMEstimator
from qiskit.quantum_info import Pauli
from qiskit.circuit import QuantumCircuit

service = IBMRuntimeService(channel="ibm_cloud", token="...", instance="...")
ibm_estimator = IBMEstimator(service=service, backend="ibmq_qasm_simulator")

N = 12
qc = QuantumCircuit(N)
qc.x(range(N))
qc.h(range(N))
qc.ch(range(N//2,0,-1), range(N//2-1,-1,-1))
qc.ch(range(N//2, N-1), range(N//2+1,N))
qc.measure_all()
op = Pauli('Z'*12)

with ibm_estimator(circuits=[qc], observables=[op], skip_transpilation=False) as estimator:
    result = estimator(circuit_indices=[0],
                       observable_indices=[0],
                       parameter_values=None,
                       shots=1e4)
    print(estimator._session._job)
    
result
```
2. Above program throws below websockets error on IBM Cloud. This websockets issue is not happening on IBM Quantum (or IQX). This is being treated as a separate issue and is being tracked in NTC-384 on API side. So I would try debugging this hanging issue with an IBM Quantum account.
```
/var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/ipykernel_97924/3723068723.py:5: DeprecationWarning: IBMEstimator class is deprecated and will be removed in a future release. You can now use qiskit_ibm_runtime.Estimator class instead.
  ibm_estimator = IBMEstimator(service=service, backend="ibmq_qasm_simulator")
runtime_job._start_websocket_client:WARNING:2022-04-05 12:03:10,399: An error occurred while streaming results from the server for job c966d1l3umar17a8noqg:
Traceback (most recent call last):
  File "/Users/rathish/Documents/quantum/qiskit-ibm-runtime/qiskit_ibm_runtime/runtime_job.py", line 378, in _start_websocket_client
    self._ws_client.job_results()
  File "/Users/rathish/Documents/quantum/qiskit-ibm-runtime/qiskit_ibm_runtime/api/clients/runtime_ws.py", line 70, in job_results
    self.stream(url=url, retries=max_retries, backoff_factor=backoff_factor)
  File "/Users/rathish/Documents/quantum/qiskit-ibm-runtime/qiskit_ibm_runtime/api/clients/base.py", line 230, in stream
    raise WebsocketError(error_message)
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_app.py", line 383, in run_forever\n    dispatcher.read(self.sock.sock, read, check)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_app.py", line 66, in read\n    if not read_callback():\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_app.py", line 349, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_core.py", line 401, in recv_data_frame\n    frame = self.recv_frame()\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_core.py", line 440, in recv_frame\n    return self.frame_buffer.recv_frame()\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_abnf.py", line 338, in recv_frame\n    self.recv_header()\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_abnf.py", line 294, in recv_header\n    header = self.recv_strict(2)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_abnf.py", line 373, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_core.py", line 524, in _recv\n    return recv(self.sock, bufsize)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_socket.py", line 108, in recv\n    bytes_ = _recv()\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/websocket/_socket.py", line 87, in _recv\n    return sock.recv(bufsize)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/ssl.py", line 1226, in recv\n    return self.read(buflen)\n  File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/ssl.py", line 1101, in read\n    return self._sslobj.read(len)\nConnectionResetError: [Errno 54] Connection reset by peer\n'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [7], in <cell line: 16>()
     14 op = Pauli('Z'*12)
     16 with ibm_estimator(circuits=[qc], observables=[op], skip_transpilation=False) as estimator:
---> 17     result = estimator(circuit_indices=[0],
     18                        observable_indices=[0],
     19                        parameter_values=None,
     20                        shots=1e4)
     22     print(result)

File ~/Documents/quantum/qiskit-ibm-runtime/qiskit_ibm_runtime/estimator.py:228, in Estimator.__call__(self, circuit_indices, observable_indices, parameter_values, **run_options)
    220 self._session.write(
    221     circuit_indices=circuit_indices,
    222     observable_indices=observable_indices,
    223     parameter_values=parameter_values,
    224     run_options=run_options,
    225 )
    226 raw_result = self._session.read()
    227 return EstimatorResult(
--> 228     values=raw_result["values"],
    229     metadata=raw_result["metadata"],
    230 )

TypeError: string indices must be integers
```
3. It seems to start hanging at 9 qubits.

@ikkoham @t-imamichi - This info could be helpful when checking if the issues are in primitives.

**Comment by nonhermitian** [comment]
@ajavadia Yeah I guess in hindsight that makes sense because internally it is going to add post rotations and group.  It would be nice if it raised on that though since it may not be obvious to all that, for example, the Sampler needs measurements whereas the Estimator does not (at least not explicitly).

However, removing the `measure_all` does not fix the original issue here.  But my guess is it is responsible for the final `TypeError`.  Interesting that at 4Q it does not have any issues with `measure_all`

**Comment by t-imamichi** [comment]
Thank you for the report. The conversion of `Pauli` object in the estimator runtime program takes a long time. So, we will update it to avoid the long path.
As a workaround, replacing `Pauli` with `SparsePauliOp` would work.
In particular, `op = Pauli('Z'*12)` → `op = SparsePauliOp('Z'*12)`

**Comment by ajavadia** [comment]
I think this was fixed by the above commit.
