### ISSUE TITLE
[qiskit 0.33.0] Error - cannot execute a circuit-runner program 

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-ibm-runtime#53]
**Describe the bug**
circuit-runner ends in JobStatus.ERROR: 'job incurred error'
```python
RuntimeJobFailureError: 'Unable to retrieve job result. Job c6oeij749l014bc1li40 has failed:\n2021-12-08T17:20:17.898524224Z /usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py:1044: UserWarning: The qiskit version used to generate the provided QPY file, 0.19.0, is newer than the current qiskit version 0.18.3. This may result in an error if the QPY file uses instructions not present in this current qiskit version\n2021-12-08T17:20:17.898607193Z   warnings.warn(\n2021-12-08T17:20:17.900382476Z Traceback (most recent call last):\n2021-12-08T17:20:17.900445376Z   File "/code/program_starter.py", line 61, in <module>\n2021-12-08T17:20:17.900466190Z     user_params = json.loads(params, cls=RuntimeDecoder)\n2021-12-08T17:20:17.900484234Z   File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads\n2021-12-08T17:20:17.900502446Z     return cls(**kw).decode(s)\n2021-12-08T17:20:17.900524499Z   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode\n2021-12-08T17:20:17.900540271Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n2021-12-08T17:20:17.900557031Z   File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode\n2021-12-08T17:20:17.900574133Z     obj, end = self.scan_once(s, idx)\n2021-12-08T17:20:17.900591325Z   File "/usr/local/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/utils.py", line 229, in object_hook\n2021-12-08T17:20:17.900608293Z     return _decode_and_deserialize(obj_val, qpy_serialization.load)[0]\n2021-12-08T17:20:17.900624306Z   File "/usr/local/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/utils.py", line 87, in _decode_and_deserialize\n2021-12-08T17:20:17.900642771Z     orig = deserializer(buff)\n2021-12-08T17:20:17.900659013Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 1053, in load\n2021-12-08T17:20:17.900676157Z     circuits.append(_read_circuit(file_obj))\n2021-12-08T17:20:17.900692123Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 1058, in _read_circuit\n2021-12-08T17:20:17.900709416Z     header, name, metadata = _read_header(file_obj)\n2021-12-08T17:20:17.900725306Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 467, in _read_header\n2021-12-08T17:20:17.900741567Z     metadata = json.loads(metadata_raw)\n2021-12-08T17:20:17.900759109Z   File "/usr/local/lib/python3.8/json/__init__.py", line 343, in loads\n2021-12-08T17:20:17.900775347Z     s = s.decode(detect_encoding(s), \'surrogatepass\')\n2021-12-08T17:20:17.900792170Z   File "/usr/local/lib/python3.8/encodings/utf_32_be.py", line 11, in decode\n2021-12-08T17:20:17.900807579Z     return codecs.utf_32_be_decode(input, errors, True)\n2021-12-08T17:20:17.900823068Z UnicodeDecodeError: \'utf-32-be\' codec can\'t decode bytes in position 4-7: code point not in range(0x110000)\n'
```
**Steps to reproduce**

```python
circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0,1)
circ.measure_all()
```
```python
from qiskit.providers.ibmq import RunnerResult
backend=provider.backend.ibmq_qasm_simulator

program_inputs = {
    'circuits': circ,
}
options = {'backend_name': backend.name()}

job = provider.runtime.run(program_id="circuit-runner",
                           options=options,
                           inputs=program_inputs,
                          )
```

```python
result = job.result(decoder=RunnerResult)
```

**Expected behavior**
Same job runs OK in qiskit 0.32.0 & 0.32.1

**Additional Information**

- **Qiskit  version**: qiskit 0.33.0 (local and Quantum Lab)
- **Python version**: 3.8.3
- **Operating system**: W10

**Comment by LenaPer** [comment]
I have the same kind of error with the VQEProgram : 

```
---------------------------------------------------------------------------
RuntimeJobFailureError                    Traceback (most recent call last)
/opt/anaconda3/envs/qiskit33/lib/python3.8/site-packages/qiskit_nature/runtime/vqe_program.py in compute_minimum_eigenvalue(self, operator, aux_operators)
    281         try:
--> 282             result = job.result()
    283         except Exception as exc:

/opt/anaconda3/envs/qiskit33/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/runtime_job.py in result(self, timeout, wait, decoder)
    150             if self._status == JobStatus.ERROR:
--> 151                 raise RuntimeJobFailureError(f"Unable to retrieve job result. "
    152                                              f"{self.error_message()}")

RuntimeJobFailureError: 'Unable to retrieve job result. Job c6oslgutpkrb4a8528tg has failed:\n2021-12-09T09:22:16.872880026Z Traceback (most recent call last):\n2021-12-09T09:22:16.872924208Z   File "/code/program_starter.py", line 61, in <module>\n2021-12-09T09:22:16.872934511Z     user_params = json.loads(params, cls=RuntimeDecoder)\n2021-12-09T09:22:16.872940295Z   File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads\n2021-12-09T09:22:16.872948511Z     return cls(**kw).decode(s)\n2021-12-09T09:22:16.872961384Z   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode\n2021-12-09T09:22:16.872967043Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n2021-12-09T09:22:16.872970630Z   File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode\n2021-12-09T09:22:16.872979221Z     obj, end = self.scan_once(s, idx)\n2021-12-09T09:22:16.872985246Z   File "/usr/local/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/utils.py", line 229, in object_hook\n2021-12-09T09:22:16.872991404Z     return _decode_and_deserialize(obj_val, qpy_serialization.load)[0]\n2021-12-09T09:22:16.872997088Z   File "/usr/local/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/utils.py", line 87, in _decode_and_deserialize\n2021-12-09T09:22:16.873003717Z     orig = deserializer(buff)\n2021-12-09T09:22:16.873009503Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 1053, in load\n2021-12-09T09:22:16.873015140Z     circuits.append(_read_circuit(file_obj))\n2021-12-09T09:22:16.873020644Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 1058, in _read_circuit\n2021-12-09T09:22:16.873028100Z     header, name, metadata = _read_header(file_obj)\n2021-12-09T09:22:16.873033730Z   File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py", line 467, in _read_header\n2021-12-09T09:22:16.873039049Z     metadata = json.loads(metadata_raw)\n2021-12-09T09:22:16.873044260Z   File "/usr/local/lib/python3.8/json/__init__.py", line 343, in loads\n2021-12-09T09:22:16.873054760Z     s = s.decode(detect_encoding(s), \'surrogatepass\')\n2021-12-09T09:22:16.873060800Z   File "/usr/local/lib/python3.8/encodings/utf_32_be.py", line 11, in decode\n2021-12-09T09:22:16.873060856Z     return codecs.utf_32_be_decode(input, errors, True)\n2021-12-09T09:22:16.873073215Z UnicodeDecodeError: \'utf-32-be\' codec can\'t decode bytes in position 4-7: code point not in range(0x110000)\n'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-15-514be2738cef> in <module>
----> 1 runtime_result = runtime_vqe.compute_minimum_eigenvalue(hamiltonian)

/opt/anaconda3/envs/qiskit33/lib/python3.8/site-packages/qiskit_nature/runtime/vqe_program.py in compute_minimum_eigenvalue(self, operator, aux_operators)
    282             result = job.result()
    283         except Exception as exc:
--> 284             raise RuntimeError(f"The job {job.job_id()} failed unexpectedly.") from exc
    285 
    286         # re-build result from serialized return value

RuntimeError: The job c6oslgutpkrb4a8528tg failed unexpectedly.

```

**Comment by jyu00** [comment]
@fvarchon @LenaPer The error is because Qiskit Runtime is still at Qiskit 0.32, and data serialized by 0.33 QPY will not work with 0.32. We are waiting for a QPY fix in qiskit-terra before upgrading. For the time being it should work if you continue using Qiskit 0.32. I'll close this once Qiskit Runtime is updated.

**Comment by jyu00** [comment]
Qiskit Runtime has been updated to Qiskit 0.33.1. Please update your Qiskit version to 0.33.1, since it has important fixes on encoder we use to send data to Runtime. Thanks for your patience!
