### ISSUE TITLE
job.result constantly throws WebsocketError but result still returned

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#538]
**Describe the bug**

Every time I do `job.result()` I get the following:

runtime_job._start_websocket_client:WARNING:2022-09-21 12:33:37,772: An error occurred while streaming results from the server for job ccljphso2t6hsbe5u570:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit_ibm_runtime/runtime_job.py", line 452, in _start_websocket_client
    self._ws_client.job_results()
  File "/opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit_ibm_runtime/api/clients/runtime_ws.py", line 70, in job_results
    self.stream(url=url, retries=max_retries, backoff_factor=backoff_factor)
  File "/opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit_ibm_runtime/api/clients/base.py", line 230, in stream
    raise WebsocketError(error_message)
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection.'

However, the result still gets returned, e.g

```python
EstimatorResult(values=array([0.4488]), metadata=[{'variance': 0.79857856, 'shots': 10000}])
```

**Additional Information**

- **qiskit-ibm-runtime version**: master
- **Python version**: 3.10
- **Operating system**: OSX

**Comment by joeswashington** [comment]
@ChitsimranGill I am still seeing this issue. Just wanted to check if you had a chance to do a discovery on this one?

**Comment by joeswashington** [comment]
Ah ok! So it's when I submit and the job is sitting in with a callback function enabled and I am waiting on the streaming results using job.result()... if you wait long enough (meaning a backend that is busy) then you will see this. 

Here's a snippet of code:

```
    def result_callback(job_id, result):
        print(result)
    
    def calculate_kernel() -> list:
        # get indices to calculate
        row_indices, col_indices = get_indices(x_vec, y_vec, is_symmetric)
        num_qbits = X_train.shape[1]
        qc = QuantumCircuit(num_qbits)
        fmX = ZZFeatureMap(num_qbits, entanglement='linear', reps=1)
        fmY = ZZFeatureMap(num_qbits, entanglement='linear', reps=1, parameter_prefix='y')
        fm = qc.compose(fmX)
        fm = fm.compose(fmY.inverse())
        start_time = time.time()
        service = QiskitRuntimeService(instance=backend_instance, channel=backend_channel, token=environ['RUNTIME_APIKEY'])
        options = Options(optimization_level=3, resilience_level=1)
        backend = service.backend(backend_name)
        circuits = [fm.assign_parameters(np.concatenate((x,y))) for x, y in to_be_computed_data_pair]        
        with Session(service=service, backend=backend):
            sampler = Sampler(options=options)
            job = sampler.run(circuits=circuits, callback=result_callback)
            job.result()
```

**Comment by joeswashington** [comment]
And here is the error I see:
```
runtime_job._start_websocket_client:warning:2022-11-01 02:47:40,760: An error occurred while streaming results from the server for job cde68qfeprknk3c1v0c0:
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/qiskit_ibm_runtime/runtime_job.py", line 452, in _start_websocket_client
 self._ws_client.job_results()
 File "/usr/local/lib/python3.8/site-packages/qiskit_ibm_runtime/api/clients/runtime_ws.py", line 70, in job_results
 self.stream(url=url, retries=max_retries, backoff_factor=backoff_factor)
 File "/usr/local/lib/python3.8/site-packages/qiskit_ibm_runtime/api/clients/base.py", line 230, in stream
 raise WebsocketError(error_message)
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection. Error: Traceback (most recent call last):\n File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 383, in run_forever\n dispatcher.read(self.sock.sock, read, check)\n File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 66, in read\n if not read_callback():\n File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 349, in read\n op_code, frame = self.sock.recv_data_frame(True)\n File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 401, in recv_data_frame\n frame = self.recv_frame()\n File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 440, in recv_frame\n return self.frame_buffer.recv_frame()\n File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 338, in recv_frame\n self.recv_header()\n File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 294, in recv_header\n header = self.recv_strict(2)\n File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 373, in recv_strict\n bytes_ = self.recv(min(16384, shortage))\n File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 524, in _recv\n return recv(self.sock, bufsize)\n File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 122, in recv\n raise WebSocketConnectionClosedException(\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n'
```

**Comment by joeswashington** [comment]
I think this is where it is coming from:
https://github.com/Qiskit/qiskit-ibm-runtime/blob/ae64f85bff03daaec88dcd34fb3ffb178e274e1b/qiskit_ibm_runtime/api/clients/base.py#L230
