### ISSUE TITLE
test_coder_operators failing on main branch of terra

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#564]
https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/3202463779/jobs/5231471303#step:5:1067

```
ERROR: test_coder_operators (test.unit.test_data_serialization.TestDataSerialization) (operator=PauliSumOp(SparsePauliOp(['III', 'IXI', 'IYY', 'YIZ', 'XYZ', 'III'],
              coeffs=[1, 2, 3, 4, 5, 6]), coeff=10))
Test runtime encoder and decoder for operators.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/unit/test_data_serialization.py", line 179, in test_coder_operators
    self.assertEqual(operator, decoded)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/unittest/case.py", line 827, in _baseAssertEqual
    if not first == second:
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/qiskit/opflow/operator_base.py", line 240, in __eq__
    return self.equals(cast(OperatorBase, other))
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/qiskit/opflow/primitive_ops/pauli_sum_op.py", line 165, in equals
    return len(self_reduced) == len(other_reduced) and self_reduced.primitive.equiv(
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py", line 186, in equiv
    return np.allclose((self - other).simplify().coeffs, 0.0, atol=atol)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py", line 459, in simplify
    coeffs = np.array([0j], dtype=self.coeffs.dtype)
TypeError: can't convert complex to int
```

I believe it's related to https://github.com/Qiskit/qiskit-terra/pull/8620

**Comment by kt474** [comment]
closed by #578
