### ISSUE TITLE
Error while running VQE Runtime tutorial

### ISSUE THREAD

**Issue by pat-phattharaporn** [Qiskit/qiskit-ibm-runtime#572]
**Describe the bug**
Error message in Additional Information

**Steps to reproduce**
Run this [tutorial](https://github.com/Qiskit/qiskit-ibm-runtime/blob/stable/0.6/docs/tutorials/vqe.ipynb) by changing the following:
(1) backend to service.backend("simulator_statevector")
In the vqe_inputs dictionary:
(2) optimizer: from dictionary to SPSA(maxiter=50) because passing as dictionary is depreciated
(3) "measurement_error_mitigation": False because MEM can't be used with simulator_statevector

**Expected behavior**
VQE runs successfully

**Suggested solutions**
I have no idea looking at the error message. Please help!

**Additional Information**
2022-10-11T23:56:35.135252502Z jaeger_tracing - INFO Initializing Jaeger Tracer with UDP reporter
2022-10-11T23:56:35.145826413Z jaeger_tracing - INFO Using sampler ConstSampler(True)
2022-10-11T23:56:35.146700599Z jaeger_tracing - INFO opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7fd6b2870eb0>[app_name=ntc-job]
2022-10-11T23:56:35.148173771Z programruntime.program_starter_wrapper - INFO Executing program.py (job cd305be4kdfe4vbiu5e0)
2022-10-11T23:56:35.187527651Z qiskit.utils.quantum_instance - INFO 
2022-10-11T23:56:35.187608672Z Qiskit Terra version: 0.21.2
2022-10-11T23:56:35.187627367Z Backend: 'aer_simulator_statevector (<programruntime.runtime_provider.RuntimeProvider object at 0x7fd6b2882a60>)', with following setting:
2022-10-11T23:56:35.187647445Z {'basis_gates': ['ccx', 'cp', 'cswap', 'csx', 'cu', 'cu1', 'cu2', 'cu3', 'cx', 'cy', 'cz', 'delay', 'diagonal', 'h', 'id', 'initialize', 'mcp', 'mcphase', 'mcr', 'mcrx', 'mcry', 'mcrz', 'mcswap', 'mcsx', 'mcu', 'mcu1', 'mcu2', 'mcu3', 'mcx', 'mcx_gray', 'mcy', 'mcz', 'multiplexer', 'p', 'pauli', 'r', 'rx', 'rxx', 'ry', 'ryy', 'rz', 'rzx', 'rzz', 's', 'sdg', 'swap', 'sx', 'sxdg', 't', 'tdg', 'u', 'u1', 'u2', 'u3', 'unitary', 'x', 'y', 'z', 'for_loop', 'if_else', 'kraus', 'qerror_loc', 'quantum_channel', 'roerror', 'save_amplitudes', 'save_amplitudes_sq', 'save_density_matrix', 'save_expval', 'save_expval_var', 'save_probabilities', 'save_probabilities_dict', 'save_state', 'save_statevector', 'save_statevector_dict', 'set_statevector', 'while_loop'], 'coupling_map': None}
2022-10-11T23:56:35.187663887Z {'initial_layout': None, 'seed_transpiler': None, 'optimization_level': None}
2022-10-11T23:56:35.187673832Z RunConfig(shots=1024)
2022-10-11T23:56:35.187720038Z {'timeout': None}
2022-10-11T23:56:35.187734876Z {}
2022-10-11T23:56:35.187745172Z {}
2022-10-11T23:56:35.187763038Z Measurement mitigation: None
2022-10-11T23:56:35.187792395Z /code/program.py:109: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
2022-10-11T23:56:35.187803571Z   if initial_point == "random" or initial_point is None:
2022-10-11T23:56:35.616162998Z qiskit.algorithms.minimum_eigen_solvers.vqe - INFO 
2022-10-11T23:56:35.616234263Z ==================== Setting of VQE ============================
2022-10-11T23:56:35.616264794Z Algorithm: VQE
2022-10-11T23:56:35.616278448Z -- max_evals_grouped: 32
2022-10-11T23:56:35.616288323Z -- circuit_sampler: <qiskit.opflow.converters.circuit_sampler.CircuitSampler object at 0x7fd6b1f63610>
2022-10-11T23:56:35.616293595Z -- expectation: <qiskit.opflow.expectations.pauli_expectation.PauliExpectation object at 0x7fd6b1f48640>
2022-10-11T23:56:35.616299025Z -- include_custom: False
2022-10-11T23:56:35.616303404Z -- ansatz:      ┌──────────┐┌──────────┐ ░                 ░  ┌──────────┐┌───────────┐
2022-10-11T23:56:35.616312143Z q_0: ┤ Ry(θ[0]) ├┤ Rz(θ[4]) ├─░───■─────────────░──┤ Ry(θ[8]) ├┤ Rz(θ[12]) ├
2022-10-11T23:56:35.616318755Z      ├──────────┤├──────────┤ ░ ┌─┴─┐           ░  ├──────────┤├───────────┤
2022-10-11T23:56:35.616325097Z q_1: ┤ Ry(θ[1]) ├┤ Rz(θ[5]) ├─░─┤ X ├──■────────░──┤ Ry(θ[9]) ├┤ Rz(θ[13]) ├
2022-10-11T23:56:35.616331188Z      ├──────────┤├──────────┤ ░ └───┘┌─┴─┐      ░ ┌┴──────────┤├───────────┤
2022-10-11T23:56:35.616337172Z q_2: ┤ Ry(θ[2]) ├┤ Rz(θ[6]) ├─░──────┤ X ├──■───░─┤ Ry(θ[10]) ├┤ Rz(θ[14]) ├
2022-10-11T23:56:35.616393632Z      ├──────────┤├──────────┤ ░      └───┘┌─┴─┐ ░ ├───────────┤├───────────┤
2022-10-11T23:56:35.616403764Z q_3: ┤ Ry(θ[3]) ├┤ Rz(θ[7]) ├─░───────────┤ X ├─░─┤ Ry(θ[11]) ├┤ Rz(θ[15]) ├
2022-10-11T23:56:35.616411119Z      └──────────┘└──────────┘ ░           └───┘ ░ └───────────┘└───────────┘
2022-10-11T23:56:35.616419782Z -- optimizer: <qiskit.algorithms.optimizers.spsa.SPSA object at 0x7fd6b291b160>
2022-10-11T23:56:35.616426168Z -- initial_point: [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
2022-10-11T23:56:35.616432798Z  0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
2022-10-11T23:56:35.616440486Z  0.00394827 0.51219226 0.81262096 0.61252607]
2022-10-11T23:56:35.616447165Z -- gradient: None
2022-10-11T23:56:35.616453153Z -- quantum_instance: 
2022-10-11T23:56:35.616459240Z Qiskit Terra version: 0.21.2
2022-10-11T23:56:35.616477518Z Backend: 'aer_simulator_statevector (<programruntime.runtime_provider.RuntimeProvider object at 0x7fd6b2882a60>)', with following setting:
2022-10-11T23:56:35.616498651Z {'basis_gates': ['ccx', 'cp', 'cswap', 'csx', 'cu', 'cu1', 'cu2', 'cu3', 'cx', 'cy', 'cz', 'delay', 'diagonal', 'h', 'id', 'initialize', 'mcp', 'mcphase', 'mcr', 'mcrx', 'mcry', 'mcrz', 'mcswap', 'mcsx', 'mcu', 'mcu1', 'mcu2', 'mcu3', 'mcx', 'mcx_gray', 'mcy', 'mcz', 'multiplexer', 'p', 'pauli', 'r', 'rx', 'rxx', 'ry', 'ryy', 'rz', 'rzx', 'rzz', 's', 'sdg', 'swap', 'sx', 'sxdg', 't', 'tdg', 'u', 'u1', 'u2', 'u3', 'unitary', 'x', 'y', 'z', 'for_loop', 'if_else', 'kraus', 'qerror_loc', 'quantum_channel', 'roerror', 'save_amplitudes', 'save_amplitudes_sq', 'save_density_matrix', 'save_expval', 'save_expval_var', 'save_probabilities', 'save_probabilities_dict', 'save_state', 'save_statevector', 'save_statevector_dict', 'set_statevector', 'while_loop'], 'coupling_map': None}
2022-10-11T23:56:35.616505191Z {'initial_layout': None, 'seed_transpiler': None, 'optimization_level': None}
2022-10-11T23:56:35.616511052Z RunConfig(shots=1024)
2022-10-11T23:56:35.616517391Z {'timeout': None}
2022-10-11T23:56:35.616523335Z {}
2022-10-11T23:56:35.616529204Z {}
2022-10-11T23:56:35.616534869Z Measurement mitigation: None
2022-10-11T23:56:35.616540378Z -- eval_time: None
2022-10-11T23:56:35.616548326Z -- eval_count: 0
2022-10-11T23:56:35.616554029Z -- callback: <bound method Publisher.callback of <program.Publisher object at 0x7fd6b2882d00>>
2022-10-11T23:56:35.616560047Z ===============================================================
2022-10-11T23:56:35.616566084Z      ┌──────────┐┌──────────┐ ░                 ░  ┌──────────┐┌───────────┐
2022-10-11T23:56:35.616572124Z q_0: ┤ Ry(θ[0]) ├┤ Rz(θ[4]) ├─░───■─────────────░──┤ Ry(θ[8]) ├┤ Rz(θ[12]) ├
2022-10-11T23:56:35.616578717Z      ├──────────┤├──────────┤ ░ ┌─┴─┐           ░  ├──────────┤├───────────┤
2022-10-11T23:56:35.616627620Z q_1: ┤ Ry(θ[1]) ├┤ Rz(θ[5]) ├─░─┤ X ├──■────────░──┤ Ry(θ[9]) ├┤ Rz(θ[13]) ├
2022-10-11T23:56:35.616638649Z      ├──────────┤├──────────┤ ░ └───┘┌─┴─┐      ░ ┌┴──────────┤├───────────┤
2022-10-11T23:56:35.616646259Z q_2: ┤ Ry(θ[2]) ├┤ Rz(θ[6]) ├─░──────┤ X ├──■───░─┤ Ry(θ[10]) ├┤ Rz(θ[14]) ├
2022-10-11T23:56:35.616652870Z      ├──────────┤├──────────┤ ░      └───┘┌─┴─┐ ░ ├───────────┤├───────────┤
2022-10-11T23:56:35.616659680Z q_3: ┤ Ry(θ[3]) ├┤ Rz(θ[7]) ├─░───────────┤ X ├─░─┤ Ry(θ[11]) ├┤ Rz(θ[15]) ├
2022-10-11T23:56:35.616669173Z      └──────────┘└──────────┘ ░           └───┘ ░ └───────────┘└───────────┘===============================================================
2022-10-11T23:56:35.616675284Z Optimizer: SPSA
2022-10-11T23:56:35.616680949Z -- gradient_support_level: 1
2022-10-11T23:56:35.616686946Z -- bounds_support_level: 1
2022-10-11T23:56:35.616694605Z -- initial_point_support_level: 3
2022-10-11T23:56:35.616722712Z -- options: {}
2022-10-11T23:56:35.616729268Z -- max_evals_grouped: 32
2022-10-11T23:56:35.616735098Z -- nfev: None
2022-10-11T23:56:35.616741122Z -- smoothed_hessian: None
2022-10-11T23:56:35.616749096Z ===============================================================
2022-10-11T23:56:35.616754837Z 
2022-10-11T23:56:35.618010984Z qiskit.algorithms.optimizers.spsa - INFO SPSA: Starting calibration of learning rate and perturbation.
2022-10-11T23:56:35.620815957Z qiskit.transpiler.runningpassmanager - INFO Pass: UnitarySynthesis - 0.00358 (ms)
2022-10-11T23:56:35.620908343Z qiskit.transpiler.runningpassmanager - INFO Pass: UnrollCustomDefinitions - 0.07510 (ms)
2022-10-11T23:56:35.621154613Z qiskit.transpiler.passes.basis.basis_translator - INFO Begin BasisTranslator from source basis {('barrier', 4), ('ry', 1), ('rz', 1), ('cx', 2)} to target basis {'for_loop', 'swap', 'mcx', 'u1', 'barrier', 'save_expval', 'csx', 'h', 'save_statevector', 'save_statevector_dict', 'delay', 'snapshot', 'mcu2', 'mcphase', 'rx', 'rzz', 'cu', 'mcp', 'ry', 'set_statevector', 'sdg', 'kraus', 'mcsx', 'sxdg', 'cp', 'initialize', 'multiplexer', 'cz', 'while_loop', 'cswap', 'roerror', 'save_density_matrix', 'cy', 'mcr', 'cx', 'pauli', 's', 'cu1', 'rxx', 'mcu3', 'save_probabilities_dict', 'save_amplitudes', 't', 'unitary', 'mcx_gray', 'mcy', 'save_expval_var', 'mcu1', 'y', 'cu2', 'measure', 'quantum_channel', 'cu3', 'id', 'x', 'mcrx', 'rzx', 'mcry', 'mcu', 'if_else', 'save_state', 'ryy', 'u', 'mcz', 'save_amplitudes_sq', 'sx', 'rz', 'diagonal', 'mcrz', 'u3', 'tdg', 'ccx', 'save_probabilities', 'mcswap', 'u2', 'qerror_loc', 'z', 'r', 'reset', 'p'}.
2022-10-11T23:56:35.621311444Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation path search completed in 0.000s.
2022-10-11T23:56:35.621921852Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation paths composed in 0.000s.
2022-10-11T23:56:35.621986777Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation instructions replaced in 0.000s.
2022-10-11T23:56:35.622054328Z qiskit.transpiler.runningpassmanager - INFO Pass: BasisTranslator - 1.03498 (ms)
2022-10-11T23:56:35.622085902Z qiskit.transpiler.runningpassmanager - INFO Pass: RemoveResetInZeroState - 0.00644 (ms)
2022-10-11T23:56:35.622179727Z qiskit.transpiler.runningpassmanager - INFO Pass: Depth - 0.02813 (ms)
2022-10-11T23:56:35.622191347Z qiskit.transpiler.runningpassmanager - INFO Pass: FixedPoint - 0.00572 (ms)
2022-10-11T23:56:35.622329665Z qiskit.transpiler.runningpassmanager - INFO Pass: Size - 0.00739 (ms)
2022-10-11T23:56:35.622340852Z qiskit.transpiler.runningpassmanager - INFO Pass: FixedPoint - 0.01097 (ms)
2022-10-11T23:56:35.622394184Z qiskit.transpiler.runningpassmanager - INFO Pass: Optimize1qGatesDecomposition - 0.03934 (ms)
2022-10-11T23:56:35.622458423Z qiskit.transpiler.runningpassmanager - INFO Pass: CXCancellation - 0.03219 (ms)
2022-10-11T23:56:35.622482999Z qiskit.transpiler.runningpassmanager - INFO Pass: UnitarySynthesis - 0.00310 (ms)
2022-10-11T23:56:35.622651603Z qiskit.transpiler.runningpassmanager - INFO Pass: UnrollCustomDefinitions - 0.04339 (ms)
2022-10-11T23:56:35.622732908Z qiskit.transpiler.passes.basis.basis_translator - INFO Begin BasisTranslator from source basis {('barrier', 4), ('ry', 1), ('rz', 1), ('cx', 2)} to target basis {'for_loop', 'swap', 'mcx', 'u1', 'barrier', 'save_expval', 'csx', 'h', 'save_statevector', 'save_statevector_dict', 'delay', 'snapshot', 'mcu2', 'mcphase', 'rx', 'rzz', 'cu', 'mcp', 'ry', 'set_statevector', 'sdg', 'kraus', 'mcsx', 'sxdg', 'cp', 'initialize', 'multiplexer', 'cz', 'while_loop', 'cswap', 'roerror', 'save_density_matrix', 'cy', 'mcr', 'cx', 'pauli', 's', 'cu1', 'rxx', 'mcu3', 'save_probabilities_dict', 'save_amplitudes', 't', 'unitary', 'mcx_gray', 'mcy', 'save_expval_var', 'mcu1', 'y', 'cu2', 'measure', 'quantum_channel', 'cu3', 'id', 'x', 'mcrx', 'rzx', 'mcry', 'mcu', 'if_else', 'save_state', 'ryy', 'u', 'mcz', 'save_amplitudes_sq', 'sx', 'rz', 'diagonal', 'mcrz', 'u3', 'tdg', 'ccx', 'save_probabilities', 'mcswap', 'u2', 'qerror_loc', 'z', 'r', 'reset', 'p'}.
2022-10-11T23:56:35.622791024Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation path search completed in 0.000s.
2022-10-11T23:56:35.623218226Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation paths composed in 0.000s.
2022-10-11T23:56:35.623272106Z qiskit.transpiler.passes.basis.basis_translator - INFO Basis translation instructions replaced in 0.000s.
2022-10-11T23:56:35.623333002Z qiskit.transpiler.runningpassmanager - INFO Pass: BasisTranslator - 0.68712 (ms)
2022-10-11T23:56:35.623361503Z qiskit.transpiler.runningpassmanager - INFO Pass: Depth - 0.01788 (ms)
2022-10-11T23:56:35.623410809Z qiskit.transpiler.runningpassmanager - INFO Pass: FixedPoint - 0.00763 (ms)
2022-10-11T23:56:35.623436427Z qiskit.transpiler.runningpassmanager - INFO Pass: Size - 0.00000 (ms)
2022-10-11T23:56:35.623495425Z qiskit.transpiler.runningpassmanager - INFO Pass: FixedPoint - 0.00000 (ms)
2022-10-11T23:56:35.623568833Z qiskit.transpiler.runningpassmanager - INFO Pass: ContainsInstruction - 0.00882 (ms)
2022-10-11T23:56:35.624010165Z qiskit.compiler.transpiler - INFO Total Transpile Time - 5.06759 (ms)
2022-10-11T23:56:35.643600676Z qiskit.compiler.assembler - INFO Total Assembly Time - 0.24557 (ms)
2022-10-11T23:56:35.668426586Z --- Logging error ---
2022-10-11T23:56:35.669852541Z Traceback (most recent call last):
2022-10-11T23:56:35.669885358Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-10-11T23:56:35.669901839Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-10-11T23:56:35.669915682Z   File "/code/program.py", line 124, in main
2022-10-11T23:56:35.669930586Z     result = vqe.compute_minimum_eigenvalue(operator, aux_operators)
2022-10-11T23:56:35.669945566Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 530, in compute_minimum_eigenvalue
2022-10-11T23:56:35.669965052Z     opt_result = self.optimizer.minimize(
2022-10-11T23:56:35.669979029Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2022-10-11T23:56:35.669992690Z     get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)
2022-10-11T23:56:35.670007150Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2022-10-11T23:56:35.670037507Z     losses = _batch_evaluate(loss, points, max_evals_grouped)
2022-10-11T23:56:35.670066544Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 734, in _batch_evaluate
2022-10-11T23:56:35.670073119Z     results += function(batch).tolist()
2022-10-11T23:56:35.670079104Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 608, in energy_evaluation
2022-10-11T23:56:35.670087100Z     variance = np.real(expectation.compute_variance(sampled_expect_op))
2022-10-11T23:56:35.670093385Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 111, in compute_variance
2022-10-11T23:56:35.670099870Z     return sum_variance(exp_op)
2022-10-11T23:56:35.670106815Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 107, in sum_variance
2022-10-11T23:56:35.670112817Z     return operator.combo_fn([sum_variance(op) for op in operator.oplist])
2022-10-11T23:56:35.670118477Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 107, in <listcomp>
2022-10-11T23:56:35.670124714Z     return operator.combo_fn([sum_variance(op) for op in operator.oplist])
2022-10-11T23:56:35.670130250Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 102, in sum_variance
2022-10-11T23:56:35.670138234Z     for (b, v) in sfdict.primitive.items()
2022-10-11T23:56:35.670143669Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit_aer/backends/compatibility.py", line 59, in __getattr__
2022-10-11T23:56:35.670149129Z     return getattr(super(), attr)
2022-10-11T23:56:35.670173057Z AttributeError: 'super' object has no attribute 'items'
2022-10-11T23:56:35.670179348Z 
2022-10-11T23:56:35.670184600Z During handling of the above exception, another exception occurred:
2022-10-11T23:56:35.670189922Z 
2022-10-11T23:56:35.670196977Z Traceback (most recent call last):
2022-10-11T23:56:35.670202530Z   File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
2022-10-11T23:56:35.670208283Z     msg = self.format(record)
2022-10-11T23:56:35.670214007Z   File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
2022-10-11T23:56:35.670219570Z     return fmt.format(record)
2022-10-11T23:56:35.670225028Z   File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
2022-10-11T23:56:35.670230710Z     record.message = record.getMessage()
2022-10-11T23:56:35.670236234Z   File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
2022-10-11T23:56:35.670242976Z     msg = msg % self.args
2022-10-11T23:56:35.670248676Z TypeError: not all arguments converted during string formatting
2022-10-11T23:56:35.670253928Z Call stack:
2022-10-11T23:56:35.670259190Z   File "/code/program_starter.py", line 57, in <module>
2022-10-11T23:56:35.670264912Z     starter.execute()
2022-10-11T23:56:35.670270481Z   File "/provider/programruntime/program_starter_wrapper.py", line 94, in execute
2022-10-11T23:56:35.670276384Z     logger.error(
2022-10-11T23:56:35.670282233Z Message: 'Error executing program job cd305be4kdfe4vbiu5e0'
2022-10-11T23:56:35.670289767Z Arguments: (AttributeError("'super' object has no attribute 'items'"),)
2022-10-11T23:56:35.682873796Z jaeger_tracing - INFO Span publisher exited
2022-10-11T23:56:35.685349214Z Traceback (most recent call last):
2022-10-11T23:56:35.685380462Z   File "/code/program_starter.py", line 57, in <module>
2022-10-11T23:56:35.685548900Z     starter.execute()
2022-10-11T23:56:35.685574102Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute
2022-10-11T23:56:35.685679151Z     raise ex
2022-10-11T23:56:35.685747372Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-10-11T23:56:35.685788202Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-10-11T23:56:35.685800336Z   File "/code/program.py", line 124, in main
2022-10-11T23:56:35.685915768Z     result = vqe.compute_minimum_eigenvalue(operator, aux_operators)
2022-10-11T23:56:35.685933633Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 530, in compute_minimum_eigenvalue
2022-10-11T23:56:35.686185125Z     opt_result = self.optimizer.minimize(
2022-10-11T23:56:35.686212578Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2022-10-11T23:56:35.686461574Z     get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)
2022-10-11T23:56:35.686478249Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2022-10-11T23:56:35.686706328Z     losses = _batch_evaluate(loss, points, max_evals_grouped)
2022-10-11T23:56:35.686722732Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 734, in _batch_evaluate
2022-10-11T23:56:35.687058745Z     results += function(batch).tolist()
2022-10-11T23:56:35.687076308Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 608, in energy_evaluation
2022-10-11T23:56:35.687322116Z     variance = np.real(expectation.compute_variance(sampled_expect_op))
2022-10-11T23:56:35.687341083Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 111, in compute_variance
2022-10-11T23:56:35.687380703Z     return sum_variance(exp_op)
2022-10-11T23:56:35.687398691Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 107, in sum_variance
2022-10-11T23:56:35.687585295Z     return operator.combo_fn([sum_variance(op) for op in operator.oplist])
2022-10-11T23:56:35.687601501Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 107, in <listcomp>
2022-10-11T23:56:35.687652114Z     return operator.combo_fn([sum_variance(op) for op in operator.oplist])
2022-10-11T23:56:35.687701840Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/opflow/expectations/pauli_expectation.py", line 102, in sum_variance
2022-10-11T23:56:35.687822526Z     for (b, v) in sfdict.primitive.items()
2022-10-11T23:56:35.687839021Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit_aer/backends/compatibility.py", line 59, in __getattr__
2022-10-11T23:56:35.687872715Z     return getattr(super(), attr)
2022-10-11T23:56:35.687951237Z AttributeError: 'super' object has no attribute 'items'

- **qiskit-ibm-runtime version**: 0.6.2
- **Python version**: 3.8.10
- **Operating system**: Mac OS 12.5.1

**Comment by kt474** [comment]
This tutorial has been removed in favor of [vqe_with_estimator](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/vqe_with_estimator.ipynb), closing this issue for now
