### ISSUE TITLE
Failing/flaky integration tests

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#584]
Integration tests are failing [here](https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/3278993969/jobs/5405779461) and the tests that fail are not consistent. 

`test_estimator_callback`
`test_sampler_callback`

```
ERROR: test_estimator_callback (test.integration.test_estimator.TestIntegrationEstimator) (service=<QiskitRuntimeService>)
Test Estimator callback function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/decorators.py", line 69, in _wrapper
    func(self, *args, **kwargs)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_estimator.py", line 282, in test_estimator_callback
    self.assertEqual(result.values, ws_result[-1].values)
IndexError: list index out of range
```

`test_websocket_proxy`
```
FAIL: test_websocket_proxy (test.integration.test_results.TestIntegrationResults) (service=<QiskitRuntimeService>)
Test connecting to websocket via proxy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/decorators.py", line 69, in _wrapper
    func(self, *args, **kwargs)
  File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/integration/test_results.py", line 233, in test_websocket_proxy
    self.assertTrue(callback_called)
AssertionError: False is not true
```

`test_run_program_failed_ran_too_long`
`test_callback_error`

**Comment by jyu00** [comment]
Fixed by #588 and #591
