### ISSUE TITLE
Running circuit with qubits added directly fails

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-ibm-runtime#615]
**Describe the bug**
If you add qubits directly (rather than initializing the circuit with a register) runtime gives an error.

**Steps to reproduce**
```python
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.circuit import CircuitInstruction
from qiskit.circuit.library import Measure
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler

service = QiskitRuntimeService()
backend = service.backend("ibmq_qasm_simulator")
sampler = Sampler(session=backend)

qubits = QuantumRegister(2)
clbits = ClassicalRegister(2)

circuit = QuantumCircuit()
circuit.add_bits(qubits)
circuit.add_bits(clbits)
for q, c in zip(qubits, clbits):
    circuit.append(CircuitInstruction(Measure(), [q], [c]))

job = sampler.run(circuit)
result = job.result()
```
This results in "Failed" status. The logs from the web interface:
```
2022-11-14T11:47:54.085809525Z INFO:     Started server process [12]
2022-11-14T11:47:54.085877331Z INFO:     Waiting for application startup.
2022-11-14T11:47:54.085904817Z INFO:     Application startup complete.
2022-11-14T11:47:54.088125878Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
2022-11-14T11:47:55.537338706Z INFO:     127.0.0.1:58160 - "POST /run HTTP/1.1" 202 Accepted
2022-11-14T11:47:55.615553708Z /opt/app-root/lib64/python3.8/site-packages/qiskit_ibm_runtime/qpy/interface.py:255: UserWarning: The qiskit version used to generate the provided QPY file, 0.23.0, is newer than the current qiskit version 0.22.2. This may result in an error if the QPY file uses instructions not present in this current qiskit version
2022-11-14T11:47:55.615636276Z   warnings.warn(
2022-11-14T11:47:55.626712218Z program - WARNING Backend (qasm_simulator) does not support dynamical decoupling.
2022-11-14T11:47:55.912098487Z qiskit_aer.backends.aerbackend - WARNING Simulation failed and returned the following error message:
2022-11-14T11:47:55.912145657Z ERROR: Failed to load qobj: Invalid Qobj experiment: not enough memory slots.
2022-11-14T11:47:55.913970029Z --- Logging error ---
2022-11-14T11:47:55.915936790Z Traceback (most recent call last):
2022-11-14T11:47:55.915972036Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-11-14T11:47:55.915990887Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-14T11:47:55.916008834Z   File "/code/./program.py", line 841, in main
2022-11-14T11:47:55.916061067Z     result = sampler.run(
2022-11-14T11:47:55.916078563Z   File "/code/./program.py", line 323, in run
2022-11-14T11:47:55.916095853Z     return self._postprocessing(result, bound_circuits)
2022-11-14T11:47:55.916118593Z   File "/code/./program.py", line 429, in _postprocessing
2022-11-14T11:47:55.916136597Z     shots = sum(counts[0].values())
2022-11-14T11:47:55.916175601Z IndexError: list index out of range
2022-11-14T11:47:55.916192886Z 
2022-11-14T11:47:55.916211219Z During handling of the above exception, another exception occurred:
2022-11-14T11:47:55.916227157Z 
2022-11-14T11:47:55.916244933Z Traceback (most recent call last):
2022-11-14T11:47:55.916268573Z   File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
2022-11-14T11:47:55.916286740Z     msg = self.format(record)
2022-11-14T11:47:55.916327973Z   File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
2022-11-14T11:47:55.916348088Z     return fmt.format(record)
2022-11-14T11:47:55.916364464Z   File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
2022-11-14T11:47:55.916381002Z     record.message = record.getMessage()
2022-11-14T11:47:55.916398255Z   File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
2022-11-14T11:47:55.916420005Z     msg = msg % self.args
2022-11-14T11:47:55.916436808Z TypeError: not all arguments converted during string formatting
2022-11-14T11:47:55.916469823Z Call stack:
2022-11-14T11:47:55.919937619Z   File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
2022-11-14T11:47:55.919957609Z     self._bootstrap_inner()
2022-11-14T11:47:55.919967490Z   File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
2022-11-14T11:47:55.919978531Z     self.run()
2022-11-14T11:47:55.919988369Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-14T11:47:55.919997814Z     result = context.run(func, *args)
2022-11-14T11:47:55.920005148Z   File "/provider/server/main.py", line 72, in execute_program
2022-11-14T11:47:55.920012371Z     starter.execute()
2022-11-14T11:47:55.920020813Z   File "/provider/programruntime/program_starter_wrapper.py", line 94, in execute
2022-11-14T11:47:55.920038210Z     logger.error(
2022-11-14T11:47:55.920047010Z Message: 'Error executing program job cdp2lqn77nr2iqqhbtu0'
2022-11-14T11:47:55.920057367Z Arguments: (IndexError('list index out of range'),)
2022-11-14T11:47:55.936565146Z ERROR:    Exception in ASGI application
2022-11-14T11:47:55.936599022Z Traceback (most recent call last):
2022-11-14T11:47:55.936615601Z   File "/opt/app-root/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2022-11-14T11:47:55.936627136Z     result = await app(  # type: ignore[func-returns-value]
2022-11-14T11:47:55.936641744Z   File "/opt/app-root/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-11-14T11:47:55.936653662Z     return await self.app(scope, receive, send)
2022-11-14T11:47:55.937038687Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
2022-11-14T11:47:55.937058939Z     await super().__call__(scope, receive, send)
2022-11-14T11:47:55.937072021Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/applications.py", line 124, in __call__
2022-11-14T11:47:55.937084004Z     await self.middleware_stack(scope, receive, send)
2022-11-14T11:47:55.937094220Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-11-14T11:47:55.937104986Z     raise exc
2022-11-14T11:47:55.937116607Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-11-14T11:47:55.937125924Z     await self.app(scope, receive, _send)
2022-11-14T11:47:55.937140357Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2022-11-14T11:47:55.937150882Z     raise exc
2022-11-14T11:47:55.937162134Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2022-11-14T11:47:55.937173033Z     await self.app(scope, receive, sender)
2022-11-14T11:47:55.937183418Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-11-14T11:47:55.937193690Z     raise e
2022-11-14T11:47:55.937204951Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-11-14T11:47:55.937217523Z     await self.app(scope, receive, send)
2022-11-14T11:47:55.937230643Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 680, in __call__
2022-11-14T11:47:55.937242194Z     await route.handle(scope, receive, send)
2022-11-14T11:47:55.937252231Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 275, in handle
2022-11-14T11:47:55.937262414Z     await self.app(scope, receive, send)
2022-11-14T11:47:55.937274684Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 68, in app
2022-11-14T11:47:55.937286709Z     await response(scope, receive, send)
2022-11-14T11:47:55.937296473Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/responses.py", line 170, in __call__
2022-11-14T11:47:55.937324261Z     await self.background()
2022-11-14T11:47:55.937338971Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/background.py", line 43, in __call__
2022-11-14T11:47:55.937352826Z     await task()
2022-11-14T11:47:55.937368181Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/background.py", line 28, in __call__
2022-11-14T11:47:55.937378543Z     await run_in_threadpool(self.func, *self.args, **self.kwargs)
2022-11-14T11:47:55.937390747Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2022-11-14T11:47:55.937412913Z     return await anyio.to_thread.run_sync(func, *args)
2022-11-14T11:47:55.937425050Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
2022-11-14T11:47:55.937437534Z     return await get_asynclib().run_sync_in_worker_thread(
2022-11-14T11:47:55.937452235Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2022-11-14T11:47:55.937462480Z     return await future
2022-11-14T11:47:55.937473532Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-14T11:47:55.937503939Z     result = context.run(func, *args)
2022-11-14T11:47:55.937516736Z   File "/provider/server/main.py", line 72, in execute_program
2022-11-14T11:47:55.937527945Z     starter.execute()
2022-11-14T11:47:55.937539035Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute
2022-11-14T11:47:55.937551896Z     raise ex
2022-11-14T11:47:55.937565746Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-11-14T11:47:55.937576554Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-14T11:47:55.937590008Z   File "/code/./program.py", line 841, in main
2022-11-14T11:47:55.937601534Z     result = sampler.run(
2022-11-14T11:47:55.937613474Z   File "/code/./program.py", line 323, in run
2022-11-14T11:47:55.937623259Z     return self._postprocessing(result, bound_circuits)
2022-11-14T11:47:55.937635012Z   File "/code/./program.py", line 429, in _postprocessing
2022-11-14T11:47:55.937645960Z     shots = sum(counts[0].values())
2022-11-14T11:47:55.937902479Z IndexError: list index out of range
2022-11-14T11:47:55.937924817Z uvicorn.error - ERROR Exception in ASGI application
2022-11-14T11:47:55.937936361Z Traceback (most recent call last):
2022-11-14T11:47:55.937948608Z   File "/opt/app-root/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2022-11-14T11:47:55.937962433Z     result = await app(  # type: ignore[func-returns-value]
2022-11-14T11:47:55.937974013Z   File "/opt/app-root/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-11-14T11:47:55.938116064Z     return await self.app(scope, receive, send)
2022-11-14T11:47:55.938173102Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
2022-11-14T11:47:55.938331080Z     await super().__call__(scope, receive, send)
2022-11-14T11:47:55.938345265Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/applications.py", line 124, in __call__
2022-11-14T11:47:55.938357193Z     await self.middleware_stack(scope, receive, send)
2022-11-14T11:47:55.938368983Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-11-14T11:47:55.938380805Z     raise exc
2022-11-14T11:47:55.938392321Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-11-14T11:47:55.938403654Z     await self.app(scope, receive, _send)
2022-11-14T11:47:55.938419904Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2022-11-14T11:47:55.938431560Z     raise exc
2022-11-14T11:47:55.938457992Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2022-11-14T11:47:55.938468892Z     await self.app(scope, receive, sender)
2022-11-14T11:47:55.939333706Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-11-14T11:47:55.939353951Z     raise e
2022-11-14T11:47:55.939365694Z   File "/opt/app-root/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-11-14T11:47:55.939379453Z     await self.app(scope, receive, send)
2022-11-14T11:47:55.939409022Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 680, in __call__
2022-11-14T11:47:55.939421245Z     await route.handle(scope, receive, send)
2022-11-14T11:47:55.939431488Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 275, in handle
2022-11-14T11:47:55.939454611Z     await self.app(scope, receive, send)
2022-11-14T11:47:55.939464845Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/routing.py", line 68, in app
2022-11-14T11:47:55.939474392Z     await response(scope, receive, send)
2022-11-14T11:47:55.939486820Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/responses.py", line 170, in __call__
2022-11-14T11:47:55.939496230Z     await self.background()
2022-11-14T11:47:55.939508564Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/background.py", line 43, in __call__
2022-11-14T11:47:55.939517650Z     await task()
2022-11-14T11:47:55.939526250Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/background.py", line 28, in __call__
2022-11-14T11:47:55.939534413Z     await run_in_threadpool(self.func, *self.args, **self.kwargs)
2022-11-14T11:47:55.939543590Z   File "/opt/app-root/lib64/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2022-11-14T11:47:55.939557394Z     return await anyio.to_thread.run_sync(func, *args)
2022-11-14T11:47:55.939567943Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
2022-11-14T11:47:55.939577868Z     return await get_asynclib().run_sync_in_worker_thread(
2022-11-14T11:47:55.939591284Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2022-11-14T11:47:55.939600722Z     return await future
2022-11-14T11:47:55.939610907Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-14T11:47:55.939729988Z     result = context.run(func, *args)
2022-11-14T11:47:55.939741212Z   File "/provider/server/main.py", line 72, in execute_program
2022-11-14T11:47:55.939752183Z     starter.execute()
2022-11-14T11:47:55.939762310Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute
2022-11-14T11:47:55.939772578Z     raise ex
2022-11-14T11:47:55.939784316Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-11-14T11:47:55.939812999Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-14T11:47:55.939819909Z   File "/code/./program.py", line 841, in main
2022-11-14T11:47:55.939826482Z     result = sampler.run(
2022-11-14T11:47:55.939833426Z   File "/code/./program.py", line 323, in run
2022-11-14T11:47:55.939839296Z     return self._postprocessing(result, bound_circuits)
2022-11-14T11:47:55.939845193Z   File "/code/./program.py", line 429, in _postprocessing
2022-11-14T11:47:55.939852059Z     shots = sum(counts[0].values())
2022-11-14T11:47:55.939862688Z IndexError: list index out of range
```

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0
- **Python version**: 3.10.8
- **Operating system**: Arch Linux

**Comment by kevinsung** [comment]
The code works if you use the Sampler from Terra. So it should work on Runtime too.

**Comment by t-imamichi** [comment]
Thank you for reporting the issue. I notice that it's an issue of Aer simulator. As @kt474 pointed out, Aer seems to fail to simulate the circuit with error https://github.com/Qiskit/qiskit-ibm-runtime/issues/615#issuecomment-1317722564.
Could you report it to Aer?

```python
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.circuit import CircuitInstruction
from qiskit.circuit.library import Measure
from qiskit import Aer

qubits = QuantumRegister(2)
clbits = ClassicalRegister(2)

circuit = QuantumCircuit()
circuit.add_bits(qubits)
circuit.add_bits(clbits)
for q, c in zip(qubits, clbits):
    circuit.append(CircuitInstruction(Measure(), [q], [c]))

backend = Aer.get_backend("aer_simulator")
result = backend.run(circuit).result()
print(result)
```

output
```
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: Invalid Qobj experiment: not enough memory slots.
Result(backend_name='aer_simulator', backend_version='0.11.1', qobj_id='', job_id='f6cd28dd-eaf7-4978-b1c3-5730dc21ced0', success=False, results=[], date=2022-11-17T11:44:28.414154, status=ERROR: Failed to load qobj: Invalid Qobj experiment: not enough memory slots., header=None, metadata={}, time_taken=0.00030303001403808594)
```

**Comment by t-imamichi** [comment]
You may intend to use `add_register` instead of `add_bits`, @kevinsung?

```python
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.circuit import CircuitInstruction
from qiskit.circuit.library import Measure
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler

service = QiskitRuntimeService()
backend = service.backend("ibmq_qasm_simulator")
sampler = Sampler(session=backend)

qubits = QuantumRegister(2)
clbits = ClassicalRegister(2)

circuit = QuantumCircuit()
circuit.add_register(qubits)
circuit.add_register(clbits)
for q, c in zip(qubits, clbits):
    circuit.append(CircuitInstruction(Measure(), [q], [c]))

job = sampler.run(circuit)
result = job.result()
print(result)
```

output
```
SamplerResult(quasi_dists=[{0: 1.0}], metadata=[{'header_metadata': {}, 'shots': 4000, 'readout_mitigation_overhead': 1.0, 'readout_mitigation_time': 0.012226632999954745}])
```

**Comment by kevinsung** [comment]
Ok I opened https://github.com/Qiskit/qiskit-aer/issues/1660. We should still have an issue open to track when the issue is fixed with runtime, since it will need to pull the fixed version of aer once it exists.

**Comment by t-imamichi** [comment]
Thank you for opening an issue.
I think your code should work if you replace `add_bits` with `add_register`. Could you try it?

**Comment by kevinsung** [comment]
>I think your code should work if you replace add_bits with add_register. Could you try it?

Yes, this is a workaround, thank you. But this bug is still very annoying because it prevents the user from using `QuantumCircuit.from_instructions` because that method uses `add_bits` instead of `add_register`.

**Comment by t-imamichi** [comment]
I see. Let's wait for a fix of Aer.

**Comment by kt474** [comment]
closing, as this has been fixed on the aer side
