### ISSUE TITLE
Error when running TorchRuntimeClient

### ISSUE THREAD

**Issue by EliasCombarro** [Qiskit/qiskit-ibm-runtime#631]
**Describe the bug**

(Initially submitted to the qiskit-machine-learning GitHub. It was suggested that it should be posted here) 

When using TorchRuntimeClient, it fails with the following error (taken from the log of the job):

2022-11-16T07:37:37.332393231Z --- Logging error ---
2022-11-16T07:37:37.335383631Z Traceback (most recent call last):
2022-11-16T07:37:37.335438588Z File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-16T07:37:37.335466993Z final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-16T07:37:37.335499686Z File "/code/./program.py", line 502, in main
2022-11-16T07:37:37.335520910Z ret = trainer.train()
2022-11-16T07:37:37.335545397Z File "/code/./program.py", line 221, in train
2022-11-16T07:37:37.335625843Z loss, t_fwd, t_bckwd = self.train_step(train_batch)
2022-11-16T07:37:37.335644144Z File "/code/./program.py", line 293, in train_step
2022-11-16T07:37:37.335662319Z self.optimizer.step()
2022-11-16T07:37:37.335679267Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
2022-11-16T07:37:37.335744542Z out = func(*args, **kwargs)
2022-11-16T07:37:37.335790758Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
2022-11-16T07:37:37.335813894Z ret = func(self, *args, **kwargs)
2022-11-16T07:37:37.335837831Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/adam.py", line 214, in step
2022-11-16T07:37:37.335863581Z if self.defaults['capturable'] or self.defaults['fused']
2022-11-16T07:37:37.335885565Z KeyError: 'fused'
2022-11-16T07:37:37.335929568Z
2022-11-16T07:37:37.335946623Z During handling of the above exception, another exception occurred:
2022-11-16T07:37:37.335963172Z
2022-11-16T07:37:37.335991995Z Traceback (most recent call last):
2022-11-16T07:37:37.336010325Z File "/usr/lib64/python3.8/logging/init.py", line 1085, in emit
2022-11-16T07:37:37.336049729Z msg = self.format(record)
2022-11-16T07:37:37.336065098Z File "/usr/lib64/python3.8/logging/init.py", line 929, in format
2022-11-16T07:37:37.336082152Z return fmt.format(record)
2022-11-16T07:37:37.336198160Z File "/usr/lib64/python3.8/logging/init.py", line 668, in format
2022-11-16T07:37:37.336366939Z record.message = record.getMessage()
2022-11-16T07:37:37.336391059Z File "/usr/lib64/python3.8/logging/init.py", line 373, in getMessage
2022-11-16T07:37:37.336410227Z msg = msg % self.args
2022-11-16T07:37:37.336459186Z TypeError: not all arguments converted during string formatting
2022-11-16T07:37:37.336477951Z Call stack:
2022-11-16T07:37:37.336596920Z File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
2022-11-16T07:37:37.336679861Z self._bootstrap_inner()
2022-11-16T07:37:37.336700948Z File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
2022-11-16T07:37:37.336725819Z self.run()
2022-11-16T07:37:37.336744522Z File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-16T07:37:37.336762596Z result = context.run(func, *args)
2022-11-16T07:37:37.336780238Z File "/provider/server/main.py", line 75, in execute_program
2022-11-16T07:37:37.336797858Z starter.execute()
2022-11-16T07:37:37.336816243Z File "/provider/programruntime/program_starter_wrapper.py", line 92, in execute
2022-11-16T07:37:37.336833844Z logger.error(
2022-11-16T07:37:37.336851598Z Message: 'Error executing program job cdq96djcgdedhj0apec0'
2022-11-16T07:37:37.336873987Z Arguments: (KeyError('fused'),)
2022-11-16T07:37:37.336940229Z webserver-starter - ERROR Failed to execute program: 'fused'
2022-11-16T07:37:37.336959480Z Traceback (most recent call last):
2022-11-16T07:37:37.336977111Z File "/provider/server/main.py", line 75, in execute_program
2022-11-16T07:37:37.336998211Z starter.execute()
2022-11-16T07:37:37.337016918Z File "/provider/programruntime/program_starter_wrapper.py", line 96, in execute
2022-11-16T07:37:37.337035462Z raise ex
2022-11-16T07:37:37.337057385Z File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-16T07:37:37.337075587Z final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-16T07:37:37.337093184Z File "/code/./program.py", line 502, in main
2022-11-16T07:37:37.337108520Z ret = trainer.train()
2022-11-16T07:37:37.337127089Z File "/code/./program.py", line 221, in train
2022-11-16T07:37:37.337143146Z loss, t_fwd, t_bckwd = self.train_step(train_batch)
2022-11-16T07:37:37.337160520Z File "/code/./program.py", line 293, in train_step
2022-11-16T07:37:37.337176835Z self.optimizer.step()
2022-11-16T07:37:37.337197548Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
2022-11-16T07:37:37.337214349Z out = func(*args, **kwargs)
2022-11-16T07:37:37.337232286Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
2022-11-16T07:37:37.337544979Z ret = func(self, *args, **kwargs)
2022-11-16T07:37:37.337579685Z File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/adam.py", line 214, in step
2022-11-16T07:37:37.337602418Z if self.defaults['capturable'] or self.defaults['fused']
2022-11-16T07:37:37.337627948Z KeyError: 'fused'
2022-11-16T07:37:37.352319665Z jaeger_tracing - INFO Span publisher exited
2022-11-16T07:37:37.352881613Z webserver-starter - DEBUG Writing job status to termination marker file: '{"status": "Failed"}'

**Steps to reproduce**

I have used the code of the TorchRuntimeClient that used to be on Qiskit's website (it fails both with ibmq_qasm_simulator and all real devices I have tried):

import numpy as np
import matplotlib.pyplot as plt

from torch import Tensor, manual_seed, is_tensor
from torch.nn import Linear, CrossEntropyLoss, MSELoss
from torch.optim import LBFGS, Adam
from torch.utils.data import Dataset, DataLoader

from qiskit import Aer, QuantumCircuit
from qiskit.utils import QuantumInstance, algorithm_globals
from qiskit.opflow import AerPauliExpectation
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes, ZZFeatureMap
from qiskit_machine_learning.neural_networks import CircuitQNN, TwoLayerQNN
from qiskit_machine_learning.connectors import TorchConnector
from qiskit_machine_learning.runtime import TorchRuntimeClient, TorchRuntimeResult

seed = 42
manual_seed(seed)
algorithm_globals.random_seed = seed

**Expected behavior**

It should run without errors 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0
- **Python version**: 3.7.15
- **Operating system**: Google Colab

**Comment by EliasCombarro** [comment]
Hi, any chance of finding a solution to this issue? Thanks so much in advance!!!

**Comment by kt474** [comment]
Are you still running into the same error? I was able to run a `torch-train` job based on the code in [527](https://github.com/Qiskit/qiskit-machine-learning/issues/527). This snippet doesn't actually use `qiskit-ibm-runtime` so if it's not an issue in `qiskit-machine-learning` it's a server side issue in which case I can create an issue there.

**Comment by EliasCombarro** [comment]
Hi, thanks for taking a look at it. I have just run the code in https://github.com/Qiskit/qiskit-machine-learning/issues/527 and it still gives an error. However, the error now seems to be different. Namely, I obtain this:

2022-11-28T18:10:03.188378499Z XXX lineno: 94, opcode: 120
2022-11-28T18:10:03.188613639Z --- Logging error ---
2022-11-28T18:10:03.190209521Z Traceback (most recent call last):
2022-11-28T18:10:03.190247776Z   File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-28T18:10:03.190264607Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-28T18:10:03.190279652Z   File "/code/./program.py", line 434, in main
2022-11-28T18:10:03.190295873Z     optimizer = str_to_obj(kwargs.get("optimizer", None))
2022-11-28T18:10:03.190312774Z   File "/code/./program.py", line 533, in str_to_obj
2022-11-28T18:10:03.190327234Z     obj = dill.loads(base64.b64decode(string.encode()))
2022-11-28T18:10:03.190342775Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 387, in loads
2022-11-28T18:10:03.190368802Z     return load(file, ignore, **kwds)
2022-11-28T18:10:03.190384573Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 373, in load
2022-11-28T18:10:03.190399451Z     return Unpickler(file, ignore=ignore, **kwds).load()
2022-11-28T18:10:03.190414230Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 646, in load
2022-11-28T18:10:03.190443554Z     obj = StockUnpickler.load(self)
2022-11-28T18:10:03.190499499Z   File "/usr/local/lib/python3.7/dist-packages/torch/optim/adam.py", line 94, in __setstate__
2022-11-28T18:10:03.190516344Z SystemError: unknown opcode
2022-11-28T18:10:03.190623151Z 
2022-11-28T18:10:03.190642471Z During handling of the above exception, another exception occurred:
2022-11-28T18:10:03.190658358Z 
2022-11-28T18:10:03.190683951Z Traceback (most recent call last):
2022-11-28T18:10:03.190698909Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit
2022-11-28T18:10:03.190714201Z     msg = self.format(record)
2022-11-28T18:10:03.190729079Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format
2022-11-28T18:10:03.190744080Z     return fmt.format(record)
2022-11-28T18:10:03.190760782Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format
2022-11-28T18:10:03.190774361Z     record.message = record.getMessage()
2022-11-28T18:10:03.190793344Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage
2022-11-28T18:10:03.190810777Z     msg = msg % self.args
2022-11-28T18:10:03.190825816Z TypeError: not all arguments converted during string formatting
2022-11-28T18:10:03.190842505Z Call stack:
2022-11-28T18:10:03.190918966Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap
2022-11-28T18:10:03.190939580Z     self._bootstrap_inner()
2022-11-28T18:10:03.190952620Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
2022-11-28T18:10:03.190967463Z     self.run()
2022-11-28T18:10:03.190983386Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-28T18:10:03.190998735Z     result = context.run(func, *args)
2022-11-28T18:10:03.191013239Z   File "/provider/server/main.py", line 75, in execute_program
2022-11-28T18:10:03.191028601Z     starter.execute()
2022-11-28T18:10:03.191043892Z   File "/provider/programruntime/program_starter_wrapper.py", line 92, in execute
2022-11-28T18:10:03.191059667Z     logger.error(
2022-11-28T18:10:03.191073501Z Message: 'Error executing program job ce2fiu4gc7i7i090mu1g'
2022-11-28T18:10:03.191088677Z Arguments: (SystemError('unknown opcode'),)
2022-11-28T18:10:03.191116789Z webserver-starter - ERROR Failed to execute program: unknown opcode
2022-11-28T18:10:03.191133460Z Traceback (most recent call last):
2022-11-28T18:10:03.191147343Z   File "/provider/server/main.py", line 75, in execute_program
2022-11-28T18:10:03.191160682Z     starter.execute()
2022-11-28T18:10:03.191177891Z   File "/provider/programruntime/program_starter_wrapper.py", line 96, in execute
2022-11-28T18:10:03.191191998Z     raise ex
2022-11-28T18:10:03.191206735Z   File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-28T18:10:03.191221387Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-28T18:10:03.191235824Z   File "/code/./program.py", line 434, in main
2022-11-28T18:10:03.191252561Z     optimizer = str_to_obj(kwargs.get("optimizer", None))
2022-11-28T18:10:03.191265914Z   File "/code/./program.py", line 533, in str_to_obj
2022-11-28T18:10:03.191301022Z     obj = dill.loads(base64.b64decode(string.encode()))
2022-11-28T18:10:03.191315569Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 387, in loads
2022-11-28T18:10:03.191328690Z     return load(file, ignore, **kwds)
2022-11-28T18:10:03.191342775Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 373, in load
2022-11-28T18:10:03.191359011Z     return Unpickler(file, ignore=ignore, **kwds).load()
2022-11-28T18:10:03.191374378Z   File "/opt/app-root/lib64/python3.9/site-packages/dill/_dill.py", line 646, in load
2022-11-28T18:10:03.191389895Z     obj = StockUnpickler.load(self)
2022-11-28T18:10:03.191402921Z   File "/usr/local/lib/python3.7/dist-packages/torch/optim/adam.py", line 94, in __setstate__
2022-11-28T18:10:03.191416821Z SystemError: unknown opcode
2022-11-28T18:10:03.207245704Z jaeger_tracing - INFO Span publisher exited
2022-11-28T18:10:03.207516047Z webserver-starter - DEBUG Writing job status to termination marker file: '{"status": "Failed"}'
2022-11-28T18:10:03.207889348Z /pod-data/ CLOSE_WRITE,CLOSE terminated
2022-11-28T18:10:03.209925665Z Termination marker file found. Kill process (7).
2022-11-28T18:10:03.257637109Z /bin/bash: line 3:     7 Killed                  python -m uvicorn server.main:app --port 8081
2022-11-28T18:10:03.257918971Z Termination signal received, exited.

**Comment by EliasCombarro** [comment]
So it fails with both Qiskit Machine Learning 0.4.0 and Qiskit Machine Learning 0.5.0, but the error message is different depending on the version. 

The one I copied in the OP is with 0.5.0. The one I copied today (two messages above this) is with 0.4.0.

**Comment by kt474** [comment]
Hmm weird, I get the same error with 0.4.0 but it runs fine with 0.5.0 - have you tried updating all your dependencies?

**Comment by EliasCombarro** [comment]
I'm using a clean Google Colab session in which I just install Qiskit 0.39.2 and Qiskit Machine Learning 0.5.0.

**Comment by EliasCombarro** [comment]
Hi! It seems that the problem was that Google Colab uses PyTorch 1.12.1 and version 1.13 is needed. After updating, it runs without error!!!

Thanks for your help!

**Comment by jyu00** [comment]
@EliasCombarro Just to give you a heads up, the torch Qiskit Runtime programs (used by TorchRuntimeClients) were deprecated more than a month ago and will be removed in the near future.

**Comment by EliasCombarro** [comment]
Thanks so much for the info. But, if I do not update my Qiskit version I will still be able to use it TorchRuntimeClient, right?

**Comment by jyu00** [comment]
@EliasCombarro Unfortunately no since the programs will be removed from the server. However, `qiskit-machine-learning` has been updated to use Qiskit Runtime primitives, so I suggest you check out the tutorials there.

**Comment by EliasCombarro** [comment]
Oh, that's too bad, really :( We are finishing writing a book on QML that uses Qiskit and we use TorchRuntimeClient for an example of how to train QNNs on actual quantum hardware. 

Thanks anyway

**Comment by EliasCombarro** [comment]
Hi, again. We've been trying to train a QNN with the new Runtime services but it seems to send a bunch of independent circuit jobs instead of a Runtime program. I'd really appreciate it if you could point me to a specific tutorial in which it is explained how to train a  QNN with Runtime (we were not able to find any among the Qiskit Machine Learning tutorials). Thanks in advance!

**Comment by jyu00** [comment]
@ElePT do you know if there are tutorials on training a QNN using runtime? 

@EliasCombarro , Elena also just gave a demo on that yesterday during [Qiskit Demo day](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays#dec-8-2022). The recording should be posted shortly if you're interested.

**Comment by EliasCombarro** [comment]
Hi again!

This is the code that we have tried in order to train a VQC with Runtime: 

```from qiskit_ibm_runtime import QiskitRuntimeService, Session, Sampler, Options
from qiskit_machine_learning.algorithms.classifiers import VQC

# channel = "ibmq_quantum" gives us access to IBM's quantum computers.
service = QiskitRuntimeService(channel = "ibm_quantum")

with Session(service = service, backend = "ibmq_lima"):
    sampler = Sampler()
    vqc = VQC(sampler = sampler, num_qubits = 2)
    vqc.fit(x_tr, y_tr)´´´

However, it spawns hundreds (literally, I counted more than 400) of Runtime Sampler jobs. We did not expect that. We expect the program to be submitted in just one go and to queue just once. 

Any hint and what we could be doing wrong will be really appreciated. Thanks in advance.

**Comment by ElePT** [comment]
Hi @EliasCombarro, it looks like you were expecting the primitives to behave like an "upload yourself" runtime program, but this is not the case. 

Primitive jobs (in this case, sampler jobs) are submitted every time you do `.run()`, the idea behind the sessions is that they provide a sort of "dynamical reservation" where your jobs will not be interrupted by other jobs in the queue, but there are still "individual jobs" so to speak. So you are not doing anything wrong, this is the expected behavior.

**Comment by EliasCombarro** [comment]
OK, I see. Thanks so much for the clarification!
