### ISSUE TITLE
Estimator on ibmq_qasm_simulator with PEC - Error msg "QiskitError("Provide a coupling map")" 

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-ibm-runtime#700]
**Describe the bug**
When using Estimator (or VQE) on "ibmq_qasm_simulator" with resilience_level=3, got error msg "**QiskitError("Provide a coupling map")**"  Passing a coupling map in the simulator options doesn't work ...  fails with error below
```
RuntimeJobFailureError                    Traceback (most recent call last)
Cell In [25], line 2
      1 print(job.job_id())
----> 2 job.result()

File ~\.conda\envs\qiskit-0.39.x\lib\site-packages\qiskit_ibm_runtime\runtime_job.py:202, in RuntimeJob.result(self, timeout, decoder)
    200     if self._reason == "RAN TOO LONG":
    201         raise RuntimeJobMaxTimeoutError(error_message)
--> 202     raise RuntimeJobFailureError(
    203         f"Unable to retrieve job result. " f"{error_message}"
    204     )
    205 result_raw = self._api_client.job_results(job_id=self.job_id())
    206 self._results = _decoder.decode(result_raw) if result_raw else None

RuntimeJobFailureError: 'Unable to retrieve job result. Job cfh2cilrc8da01s3hpo0 has failed:\n2023-02-07T10:22:18.372139195Z Setting up watches.\n2023-02-07T10:22:18.372191434Z Watches established.\n2023-02-07T10:22:19.969147713Z INFO:     Started server process [7]\n2023-02-07T10:22:19.969213327Z INFO:     Waiting for application startup.\n2023-02-07T10:22:19.969323665Z INFO:     Application startup complete.\n2023-02-07T10:22:19.971151775Z INFO:     Uvicorn running on http://127.0.0.1:8081/ (Press CTRL+C to quit)\n2023-02-07T10:22:21.646955600Z INFO:     127.0.0.1:40528 - "POST /run HTTP/1.1" 202 Accepted\n2023-02-07T10:22:23.414058837Z --- Logging error ---\n2023-02-07T10:22:23.415531242Z Traceback (most recent call last):\n2023-02-07T10:22:23.415575247Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-07T10:22:23.415596115Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-07T10:22:23.415614573Z   File "/code/./program.py", line 1467, in main\n2023-02-07T10:22:23.415631640Z     result = estimator.run(\n2023-02-07T10:22:23.415649873Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 212, in run\n2023-02-07T10:22:23.415668621Z     return self._run(\n2023-02-07T10:22:23.415686430Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 230, in _run\n2023-02-07T10:22:23.415702332Z     circuit_templates = self._generate_circuit_templates(\n2023-02-07T10:22:23.415890636Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 362, in _generate_circuit_templates\n2023-02-07T10:22:23.415930237Z     transpiled_circuits = [self.transpiled_circuits[i] for i in circuit_indices]\n2023-02-07T10:22:23.415951278Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 362, in <listcomp>\n2023-02-07T10:22:23.415974082Z     transpiled_circuits = [self.transpiled_circuits[i] for i in circuit_indices]\n2023-02-07T10:22:23.415997649Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 458, in transpiled_circuits\n2023-02-07T10:22:23.416024616Z     self._transpiled_circuits = twirled_transpile(\n2023-02-07T10:22:23.416050301Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/utils/twirled_transpile.py", line 117, in twirled_transpile\n2023-02-07T10:22:23.416076339Z     layers = stratify_circuit_into_layers(\n2023-02-07T10:22:23.416100459Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/utils/stratify.py", line 383, in stratify_circuit_into_layers\n2023-02-07T10:22:23.416147480Z     raise QiskitError("Provide a coupling map")\n2023-02-07T10:22:23.416164947Z qiskit.exceptions.QiskitError: \'Provide a coupling map\'\n2023-02-07T10:22:23.416182349Z \n2023-02-07T10:22:23.416199507Z During handling of the above exception, another exception occurred:\n2023-02-07T10:22:23.416216123Z \n2023-02-07T10:22:23.416234011Z Traceback (most recent call last):\n2023-02-07T10:22:23.416252505Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit\n2023-02-07T10:22:23.416269653Z     msg = self.format(record)\n2023-02-07T10:22:23.416285822Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format\n2023-02-07T10:22:23.416302906Z     return fmt.format(record)\n2023-02-07T10:22:23.416321759Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format\n2023-02-07T10:22:23.416337092Z     record.message = record.getMessage()\n2023-02-07T10:22:23.416353907Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage\n2023-02-07T10:22:23.416370778Z     msg = msg % self.args\n2023-02-07T10:22:23.416387997Z TypeError: not all arguments converted during string formatting\n2023-02-07T10:22:23.416405838Z Call stack:\n2023-02-07T10:22:23.416932791Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap\n2023-02-07T10:22:23.416992490Z     self._bootstrap_inner()\n2023-02-07T10:22:23.417012302Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner\n2023-02-07T10:22:23.417032300Z     self.run()\n2023-02-07T10:22:23.417066211Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run\n2023-02-07T10:22:23.417086248Z     result = context.run(func, *args)\n2023-02-07T10:22:23.417103437Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-07T10:22:23.417122062Z     starter.execute()\n2023-02-07T10:22:23.417140541Z   File "/provider/programruntime/program_starter_wrapper.py", line 95, in execute\n2023-02-07T10:22:23.417155974Z     logger.error(\n2023-02-07T10:22:23.417172376Z Message: \'Error executing program job cfh2cilrc8da01s3hpo0\'\n2023-02-07T10:22:23.417189149Z Arguments: (QiskitError(\'Provide a coupling map\'),)\n2023-02-07T10:22:23.418006248Z webserver-starter - ERROR Failed to execute program: \'Provide a coupling map\'\n2023-02-07T10:22:23.418056348Z Traceback (most recent call last):\n2023-02-07T10:22:23.418083534Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-07T10:22:23.418111126Z     starter.execute()\n2023-02-07T10:22:23.418137707Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute\n2023-02-07T10:22:23.418165769Z     raise ex\n2023-02-07T10:22:23.418188338Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-07T10:22:23.418237664Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-07T10:22:23.418257196Z   File "/code/./program.py", line 1467, in main\n2023-02-07T10:22:23.418274821Z     result = estimator.run(\n2023-02-07T10:22:23.418293255Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 212, in run\n2023-02-07T10:22:23.418312197Z     return self._run(\n2023-02-07T10:22:23.418329444Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 230, in _run\n2023-02-07T10:22:23.418347216Z     circuit_templates = self._generate_circuit_templates(\n2023-02-07T10:22:23.418364512Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 362, in _generate_circuit_templates\n2023-02-07T10:22:23.418381833Z     transpiled_circuits = [self.transpiled_circuits[i] for i in circuit_indices]\n2023-02-07T10:22:23.418402386Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 362, in <listcomp>\n2023-02-07T10:22:23.418418615Z     transpiled_circuits = [self.transpiled_circuits[i] for i in circuit_indices]\n2023-02-07T10:22:23.418436182Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/primitives/estimator.py", line 458, in transpiled_circuits\n2023-02-07T10:22:23.418453307Z     self._transpiled_circuits = twirled_transpile(\n2023-02-07T10:22:23.418471556Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/utils/twirled_transpile.py", line 117, in twirled_transpile\n2023-02-07T10:22:23.418488291Z     layers = stratify_circuit_into_layers(\n2023-02-07T10:22:23.418505413Z   File "/opt/app-root/lib64/python3.9/site-packages/pec_runtime/utils/stratify.py", line 383, in stratify_circuit_into_layers\n2023-02-07T10:22:23.418522642Z     raise QiskitError("Provide a coupling map")\n2023-02-07T10:22:23.418539876Z qiskit.exceptions.QiskitError: \'Provide a coupling map\'\n2023-02-07T10:22:23.435801441Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-02-07T10:22:23.437884008Z Termination marker file found. Kill process (7).\n2023-02-07T10:22:23.466715539Z Termination signal received, exited.\n2023-02-07T10:22:23.466716211Z /bin/bash: line 3:     7 Killed                  python -m uvicorn server.main:app --port 8081\n'
```
**Steps to reproduce**
```
from qiskit_ibm_runtime import Sampler, Estimator, Session, QiskitRuntimeService, Options 
from qiskit.quantum_info import SparsePauliOp
from qiskit.providers.fake_provider import FakeManila
from qiskit_aer.noise import NoiseModel
import numpy as np

service = QiskitRuntimeService(channel="ibm_quantum", token='')

# set up ansatz
from qiskit.circuit.library import TwoLocal
num_qubits = 2
ansatz = TwoLocal(num_qubits, "ry", "cz")

# define initial point
init_pt = [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1]

# hamiltonian
hamiltonian = SparsePauliOp.from_list(
    [
        ("II", -1.052373245772859),
        ("IZ", 0.39793742484318045),
        ("ZI", -0.39793742484318045),
        ("ZZ", -0.01128010425623538),
        ("XX", 0.18093119978423156),
    ]
)

# Import FakeBackend
fake_backend = FakeManila()
noise_model = NoiseModel.from_backend(fake_backend)

# Set options to include noise_model and resilience_level
options_with_pec = Options(simulator={
    "noise_model": noise_model,
    "seed_simulator": 42,
    "coupling_map": fake_backend.configuration().coupling_map,
    "basis_gates": fake_backend.configuration().basis_gates,
    }, resilience_level=3, optimization_level=0)

parameters = np.reshape(init_pt, (-1, len(init_pt))).tolist()
batch_size = len(parameters)

with Session(service=service, backend="ibmq_qasm_simulator") as session:
    estimator = Estimator(session=session,options=options_with_pec)
    job = estimator.run(ansatz, hamiltonian, parameter_values=parameters)

print(job.job_id())
job.result()
```

**Expected behavior**
Take into account the coupling map 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: qiskit-ibm-runtime 0.8.0   'qiskit-terra': '0.22.2' 
- **Python version**: 3.10 
- **Operating system**: Win11

**Comment by kt474** [comment]
Related to https://github.com/Qiskit/qiskit-ibm-runtime/issues/561

**Comment by kt474** [comment]
This is an issue on the primitives side, PEC for simulators is currently not supported. The simulator doesn't have a coupling map because all the qubits are connected to each other.

**Comment by jyu00** [comment]
This is now fixed, as long as a coupling map is provided
