### ISSUE TITLE
Estimator fails when given circuit with classical bits

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-ibm-runtime#749]
**Describe the bug**
In some cases, when defining the input circuit with classical bits, the Estimator gives an ugly and not so comprehensible error message.

**Steps to reproduce**
Here is a small example:
```
from qiskit_ibm_runtime import QiskitRuntimeService, Estimator
from qiskit import QuantumCircuit
from qiskit.quantum_info import SparsePauliOp

service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.backend("ibmq_qasm_simulator")

circuit = QuantumCircuit(2, 2)
obs =SparsePauliOp.from_list([("II", 1)])
backend = service.backend("ibmq_qasm_simulator")
estimator = Estimator(session=backend)
job = estimator.run(circuit, observables=obs)
print(job.result())
```
Here is the error message:
```
Traceback (most recent call last):
  File "/home/merav/work/qiskit_ibm_runtime/641/../tests/bad_classical_bits.py", line 13, in <module>
    print(job.result())
  File "/home/merav/work/qiskit_ibm_runtime/641/qiskit_ibm_runtime/runtime_job.py", line 224, in result
    raise RuntimeJobFailureError(
qiskit_ibm_runtime.exceptions.RuntimeJobFailureError: 'Unable to retrieve job result. Job cg8300fnjktevf0coth0 has failed:\nTraceback (most recent call last):\n2023-03-14T08:27:47.718414965Z   File "/provider/server/main.py", line 75, in execute_program\n2023-03-14T08:27:47.718431697Z     starter.execute()\n2023-03-14T08:27:47.718463691Z   File "/provider/programruntime/program_starter_wrapper.py", line 102, in execute\n2023-03-14T08:27:47.718487521Z     raise ex\n2023-03-14T08:27:47.718514727Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-03-14T08:27:47.718537561Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-03-14T08:27:47.718563651Z   File "/code/./program.py", line 1406, in main\n2023-03-14T08:27:47.718589310Z     result = estimator.run(\n2023-03-14T08:27:47.718609411Z   File "/code/./program.py", line 208, in run\n2023-03-14T08:27:47.718629381Z     transpiled_circuits = self.transpiled_circuits\n2023-03-14T08:27:47.718648865Z   File "/code/./program.py", line 391, in transpiled_circuits\n2023-03-14T08:27:47.718669984Z     self._split_transpile()\n2023-03-14T08:27:47.718712337Z   File "/code/./program.py", line 434, in _split_transpile\n2023-03-14T08:27:47.718772540Z     self._transpiled_circuits += self._combine(\n2023-03-14T08:27:47.718789950Z   File "/code/./program.py", line 447, in _combine\n2023-03-14T08:27:47.718804788Z     transpiled_circuit.add_register(creg)\n2023-03-14T08:27:47.718820991Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1395, in add_register\n2023-03-14T08:27:47.718837904Z     raise CircuitError(\'register name "%s" already exists\' % register.name)\n2023-03-14T08:27:47.718852892Z qiskit.circuit.exceptions.CircuitError: \'register name "c" already exists\'\n2023-03-14T08:27:47.726076677Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-03-14T08:27:47.759057309Z Termination marker file found. Kill process (7).\n2023-03-14T08:27:47.791350105Z /bin/bash: line 3:     7 Killed                  python -m uvicorn server.main:app --port 8081\n2023-03-14T08:27:47.791445470Z Termination signal received, exited.\n'
```
**Expected behavior**
Should give appropriate error message or not fail.

**Suggested solutions**

**Additional Information**
In the code above, when we define the `circuit = QuantumCircuit(2)` there is no problem.
See also #659 .

- **qiskit-ibm-runtime version**:  0.20.1
- **Python version**: 3.10.9
- **Operating system**: ubuntu

**Comment by merav-aharoni** [comment]
See epic https://github.ibm.com/IBM-Q-Software/ws-primitives/issues/39.

**Comment by frankharkins** [comment]
Even worse is that if the circuit is created with `ClassicalRegister` arguments (rather than `int`s), the job completes but with nonsense results:

| backend | cbit? | values 
|---------|-------|--------------------------
| sim     | no    | `[-1.     -0.0035]`
| kyoto   | no    | `[-1.01559967 -0.04368171]`
| sim     | yes   | `[-1.     -0.0265]`
| kyoto   | yes   | `[1.64630225 1.64630225]`

<details>
  <summary>Code to reproduce</summary>

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.quantum_info import SparsePauliOp
from qiskit_ibm_runtime import QiskitRuntimeService, Estimator

service = QiskitRuntimeService(channel="ibm_quantum")
simulator = service.backend("ibmq_qasm_simulator")
hardware = service.backend("ibm_kyoto")

mps = [SparsePauliOp("Z"), SparsePauliOp("Y")]

without_bit = QuantumCircuit(QuantumRegister(1))
without_bit.x(0)

with_bit = QuantumCircuit(QuantumRegister(1), ClassicalRegister(1))
with_bit.x(0)

jobs = []
for circuit in [without_bit, with_bit]:
    for backend in [simulator, hardware]:
        jobs.append(
            Estimator(backend=backend).run([circuit, circuit], mps)
        )
print([job.job_id() for job in jobs])
# ['clp18fb537dd6q5ve060', 'cns18fsxg8g00083720g', 'clp18g7cftmaupnofdq0', 'cns18gjnv6t0008zpq1g']

print(
f"""
| backend | cbit? | values 
|---------|-------|--------------------------
| sim     | no    | `{service.job(jobs[0]).result().values}`
| kyoto   | no    | `{service.job(jobs[1]).result().values}`
| sim     | yes   | `{service.job(jobs[2]).result().values}`
| kyoto   | yes   | `{service.job(jobs[3]).result().values}`
"""
)
```
</details>

Client-side validation would best as it can take hours for the job to run and return the error message.
